const questions=[
 {category:'SUA ROTINA',title:'Hoje você sente que...',hint:'Escolha a opção que mais se aproxima da sua realidade.',options:[['Minha vida está organizada',{organization:90,focus:80}],['Organizo algumas coisas',{organization:65,focus:58}],['Vivo esquecendo tarefas',{organization:32,focus:36}],['Não consigo manter rotina',{organization:18,habits:20,focus:25}]]},
 {category:'SEU DINHEIRO',title:'Como você controla seu dinheiro?',hint:'Não existe resposta certa. Queremos entender seu ponto de partida.',options:[['Planilha',{finance:72}],['Aplicativo financeiro',{finance:78}],['Apenas pelo banco',{finance:48}],['Não controlo',{finance:16}]]},
 {category:'SUA CONSTÂNCIA',title:'Você consegue manter hábitos?',hint:'Pense nos últimos 30 dias.',options:[['Todos os dias',{habits:90}],['Algumas vezes por semana',{habits:62}],['Quase nunca',{habits:28}],['Ainda não comecei',{habits:14}]]},
 {category:'O QUE ESCAPA',title:'O que você costuma esquecer?',hint:'Você pode marcar mais de uma opção.',multi:true,options:[['Contas',{finance:22}],['Compromissos',{organization:28}],['Estudos',{focus:30}],['Exercícios',{habits:25}],['Metas',{goals:20}],['Nada disso',{organization:88,finance:82,habits:82,goals:82,focus:82}]]},
 {category:'SUA PRIORIDADE',title:'O que você mais gostaria de melhorar?',hint:'Essa resposta personaliza seu plano final.',focus:true,options:[['Produtividade',{focus:42}],['Dinheiro',{finance:42}],['Disciplina',{habits:42}],['Organização',{organization:42}],['Tudo ao mesmo tempo',{organization:38,finance:38,habits:38,goals:38,focus:38}]]},
 {category:'SUAS FERRAMENTAS',title:'Quantos aplicativos você usa para se organizar?',hint:'Inclua agenda, notas, tarefas, hábitos e finanças.',apps:true,options:[['Apenas 1',{organization:75},1],['2 aplicativos',{organization:62},2],['3 aplicativos',{organization:48},3],['Mais de 5',{organization:30},6]]},
 {category:'SEU FUTURO',title:'Qual é seu principal objetivo para o próximo ano?',hint:'Vamos conectar o diagnóstico ao destino que mais importa.',goal:true,options:[['Guardar dinheiro',{finance:52,goals:58}],['Criar uma rotina',{organization:52,habits:55}],['Estudar com constância',{focus:55,habits:52}],['Melhorar meus hábitos',{habits:58}],['Organizar tudo',{organization:45,finance:45,habits:45,goals:45,focus:45}]]}
];
const labels={organization:['Organização','▦'],finance:['Finanças','⌁'],habits:['Hábitos','✦'],goals:['Metas','◎'],focus:['Foco','◷']};
const state={index:0,answers:Array(questions.length).fill(null),focus:'Organização',goal:'Organizar tudo',apps:3};
const screens=[...document.querySelectorAll('.screen')];
const show=id=>{screens.forEach(screen=>screen.classList.toggle('active',screen.id===id));scrollTo({top:0,behavior:'auto'})};
function renderQuestion(){const question=questions[state.index],answer=state.answers[state.index];document.getElementById('progressLabel').textContent=`PERGUNTA ${state.index+1} DE ${questions.length}`;document.getElementById('progressPercent').textContent=`${Math.round((state.index+1)/questions.length*100)}%`;document.getElementById('progressBar').style.width=`${(state.index+1)/questions.length*100}%`;document.getElementById('previousQuestion').style.visibility=state.index?'visible':'hidden';document.getElementById('questionCategory').textContent=question.category;document.getElementById('questionTitle').textContent=question.title;document.getElementById('questionHint').textContent=question.hint;document.getElementById('answers').innerHTML=question.options.map((option,index)=>{const selected=question.multi?Array.isArray(answer)&&answer.includes(index):answer===index;return `<button class="answer ${question.multi?'multi':''} ${selected?'selected':''}" data-answer="${index}"><i>${selected?'✓':''}</i><b>${option[0]}</b></button>`}).join('');document.getElementById('nextQuestion').hidden=!question.multi||!Array.isArray(answer)||!answer.length}
function advance(){if(state.index<questions.length-1){state.index++;renderQuestion()}else processResults()}
document.getElementById('answers').onclick=event=>{const button=event.target.closest('[data-answer]');if(!button)return;const option=+button.dataset.answer,question=questions[state.index];if(question.multi){let selected=Array.isArray(state.answers[state.index])?[...state.answers[state.index]]:[];if(option===question.options.length-1)selected=[option];else{selected=selected.filter(index=>index!==question.options.length-1);selected=selected.includes(option)?selected.filter(index=>index!==option):[...selected,option]}state.answers[state.index]=selected;renderQuestion();return}state.answers[state.index]=option;if(question.focus)state.focus=question.options[option][0];if(question.goal)state.goal=question.options[option][0];if(question.apps)state.apps=question.options[option][2];setTimeout(advance,180)};
document.getElementById('nextQuestion').onclick=advance;document.getElementById('previousQuestion').onclick=()=>{if(state.index){state.index--;renderQuestion()}};document.getElementById('startSurvey').onclick=()=>{show('quiz');renderQuestion()};
function calculate(){const values=Object.fromEntries(Object.keys(labels).map(key=>[key,[]]));questions.forEach((question,index)=>{const answer=state.answers[index],selected=question.multi?(answer||[]):[answer];selected.filter(Number.isInteger).forEach(value=>Object.entries(question.options[value]?.[1]||{}).forEach(([key,score])=>values[key]?.push(score)))});const scores={};Object.keys(values).forEach(key=>{const list=values[key];scores[key]=Math.max(8,Math.min(96,Math.round(list.length?list.reduce((sum,value)=>sum+value,0)/list.length:50)))});return{scores,general:Math.round(Object.values(scores).reduce((sum,value)=>sum+value,0)/5)}}
const resultCopy=score=>score<=35?['Explorador','Você percebe que precisa de uma direção mais clara. Seu ponto forte é estar disposto a descobrir um sistema que funcione para sua realidade.']:score<=55?['Organizador','Você já movimenta áreas importantes, mas ainda perde energia alternando ferramentas e tentando manter tudo conectado.']:score<=75?['Evoluidor','Você possui uma base consistente e está pronto para transformar registros separados em uma evolução visível e duradoura.']:['Astronauta','Sua organização já é forte. O próximo passo é preservar o histórico, enxergar relações entre áreas e evoluir com menos esforço.'];
function buildResult(){const{scores,general}=calculate(),[name,description]=resultCopy(general),ranked=Object.entries(scores).sort((a,b)=>a[1]-b[1]),compatibility=Math.min(98,Math.max(82,Math.round(80+(100-general)*.18))),hours=state.apps>=6?4:state.apps>=3?3:state.apps===2?2:1;document.getElementById('profileName').textContent=name;document.getElementById('profileDescription').textContent=description;document.getElementById('compatibilityValue').textContent=`${compatibility}%`;document.getElementById('generalScore').textContent=general;document.getElementById('scoreRing').style.setProperty('--score-angle',`${general*3.6}deg`);document.getElementById('scoreGrid').innerHTML=Object.entries(scores).map(([key,value])=>`<article class="score-item"><i>${labels[key][1]}</i><b>${value}/100</b><span>${labels[key][0]}</span><u style="--score:${value}%"></u></article>`).join('');document.getElementById('diagnosisList').innerHTML=ranked.slice(0,3).map(([key,value])=>`<li>${value<40?'Criar uma base para':'Fortalecer'} ${labels[key][0].toLowerCase()} com passos visíveis e simples.</li>`).join('');document.getElementById('appsToday').textContent=state.apps>=6?'Mais de 5 aplicativos hoje':`${state.apps} ${state.apps===1?'aplicativo':'aplicativos'} hoje`;document.getElementById('timeEstimate').innerHTML=`até ${hours} ${hours===1?'hora':'horas'}<small>por mês em organização</small>`;const weakest=labels[ranked[0][0]][0];document.getElementById('dashboardFocus').textContent=`FOCO RECOMENDADO · ${weakest.toUpperCase()}`;document.getElementById('dashScore').textContent=`${general} pontos`;document.getElementById('nextStep').textContent={Organização:'Definir três prioridades',Finanças:'Registrar ganhos e gastos',Hábitos:'Começar um hábito simples',Metas:'Criar uma meta mensurável',Foco:'Fazer uma sessão de 10 minutos'}[weakest];localStorage.setItem('luar-survey-result',JSON.stringify({scores,general,profile:name,focus:state.focus,goal:state.goal,createdAt:new Date().toISOString()}))}
function processResults(){show('processing');const items=[...document.querySelectorAll('.processing-list p')],bar=document.getElementById('processingBar');items.forEach((item,index)=>item.className=index?'':'active');bar.style.width='0';items.forEach((item,index)=>setTimeout(()=>{items.forEach((node,nodeIndex)=>{node.classList.toggle('done',nodeIndex<index);node.classList.toggle('active',nodeIndex===index)});bar.style.width=`${(index+1)/items.length*100}%`},index*850));setTimeout(()=>{buildResult();show('result')},3700)}
document.getElementById('restartSurvey').onclick=()=>{state.index=0;state.answers=Array(questions.length).fill(null);show('intro')};
