(() => {
  'use strict';

  const STORAGE_KEY = 'luar-language-v1';
  const LANGUAGES = Object.freeze({
    pt: { locale: 'pt-BR', flag: '🇧🇷', nativeName: 'Português', country: 'Brasil' },
    en: { locale: 'en-US', flag: '🇺🇸', nativeName: 'English', country: 'United States' },
    ru: { locale: 'ru-RU', flag: '🇷🇺', nativeName: 'Русский', country: 'Россия' }
  });

  const ENTRIES = [
    ['Experiência','Experience','Возможности'],['Sem × Com','Without × With','Без × С'],['Recursos','Features','Функции'],['Tudo incluso','Everything included','Всё включено'],['Vitalício','Lifetime','Навсегда'],['Entrar','Sign in','Войти'],['Criar conta grátis','Create free account','Создать бесплатно'],['Meu perfil','My profile','Мой профиль'],['Abrir visão geral','Open overview','Открыть обзор'],
    ['LUAR | Dinheiro, metas, hábitos, tarefas e evolução em uma única órbita.','LUAR | Money, goals, habits, tasks and progress in one orbit.','LUAR | Деньги, цели, привычки, задачи и развитие на одной орбите.'],['Pare de usar vários aplicativos.','Stop using multiple apps.','Перестаньте использовать множество приложений.'],['Coloque sua vida em ordem.','Put your life in order.','Наведите порядок в своей жизни.'],['O LUAR reúne tudo o que move sua vida e transforma registros soltos em clareza, constância e uma evolução que você nunca perde.','LUAR brings together everything that moves your life and turns scattered records into clarity, consistency and progress you never lose.','LUAR объединяет всё, что движет вашей жизнью, и превращает разрозненные записи в ясность, постоянство и прогресс, который не потеряется.'],['Começar gratuitamente','Start for free','Начать бесплатно'],['Descobrir meu índice de organização →','Discover my organization score →','Узнать мой индекс организованности →'],['Sem cartão · experimente primeiro · Vitalício por R$ 39,90 uma única vez','No card · try it first · Lifetime for a one-time R$ 39.90','Без карты · сначала попробуйте · Навсегда за разовый платёж R$ 39,90'],['VITALÍCIO NO LANÇAMENTO','LAUNCH LIFETIME OFFER','БЕССРОЧНО НА СТАРТЕ'],['depois R$ 79,90','then R$ 79.90','потом R$ 79,90'],['Sem assinatura →','No subscription →','Без подписки →'],['◇ Criado para uso próprio','◇ Built for personal use','◇ Создано для себя'],['↻ Atualizado constantemente','↻ Constantly updated','↻ Постоянно обновляется'],['✦ Desenvolvido por quem usa todos os dias','✦ Built by someone who uses it every day','✦ Создано тем, кто пользуется каждый день'],
    ['CLAREZA FINANCEIRA','FINANCIAL CLARITY','ФИНАНСОВАЯ ЯСНОСТЬ'],['Entenda para onde seu dinheiro vai.','Understand where your money goes.','Поймите, куда уходят ваши деньги.'],['Registre ganhos, gastos, metas e orçamento em uma visão simples.','Track income, expenses, goals and budget in one simple view.','Учитывайте доходы, расходы, цели и бюджет в одном понятном обзоре.'],['ROTINA CONSISTENTE','CONSISTENT ROUTINE','СТАБИЛЬНЫЙ РЕЖИМ'],['Transforme intenção em progresso.','Turn intention into progress.','Превратите намерение в прогресс.'],['Hábitos, tarefas, foco e sequência diária trabalhando juntos.','Habits, tasks, focus and daily streaks working together.','Привычки, задачи, фокус и ежедневная серия работают вместе.'],['EVOLUÇÃO VISÍVEL','VISIBLE PROGRESS','ВИДИМЫЙ ПРОГРЕСС'],['Veja cada pequeno passo crescer.','Watch every small step grow.','Наблюдайте, как растёт каждый маленький шаг.'],['Acompanhe gráficos, metas, XP e conquistas sem perder a tranquilidade.','Track charts, goals, XP and achievements without losing peace of mind.','Следите за графиками, целями, опытом и достижениями без лишнего напряжения.'],
    ['Veja tarefas, hábitos, dinheiro, foco, XP e conquistas ganhando vida ao mesmo tempo.','See tasks, habits, money, focus, XP and achievements come alive together.','Смотрите, как задачи, привычки, деньги, фокус, опыт и достижения оживают вместе.'],['Visão geral','Overview','Обзор'],['Financeiro','Finances','Финансы'],['Assinaturas','Subscriptions','Подписки'],['ORGANIZAÇÃO','ORGANIZATION','ОРГАНИЗАЦИЯ'],['Tarefas','Tasks','Задачи'],['Hábitos','Habits','Привычки'],['Agenda','Calendar','Календарь'],['Metas','Goals','Цели'],['Nova conquista desbloqueada','New achievement unlocked','Открыто новое достижение'],['agora','now','сейчас'],['HOJE, SUA JORNADA','TODAY, YOUR JOURNEY','СЕГОДНЯ, ВАШ ПУТЬ'],['Boa tarde, viajante ✦','Good afternoon, traveler ✦','Добрый день, путешественник ✦'],['＋ Adicionar registro','＋ Add entry','＋ Добавить запись'],['✓ Concluir tarefa','✓ Complete task','✓ Завершить задачу'],['✦ Completar hábito','✦ Complete habit','✦ Выполнить привычку'],['◷ Iniciar foco','◷ Start focus','◷ Начать фокус'],['☼ Alternar tema','☼ Change theme','☼ Сменить тему'],['Criar minha conta','Create my account','Создать аккаунт'],['Ganhos do mês','Monthly income','Доход за месяц'],['Gastos do mês','Monthly expenses','Расходы за месяц'],['Entradas','Income','Поступления'],['Saídas','Expenses','Расходы'],['Hábitos hoje','Habits today','Привычки сегодня'],['SEU DIA EM ÓRBITA','YOUR DAY IN ORBIT','ВАШ ДЕНЬ НА ОРБИТЕ'],['Rotina em movimento','Routine in motion','Режим в движении'],['Continue assim. Sua sequência está crescendo.','Keep going. Your streak is growing.','Продолжайте. Ваша серия растёт.'],['ORÇAMENTO','BUDGET','БЮДЖЕТ'],['Finanças em equilíbrio','Balanced finances','Финансы в равновесии'],['FOCO','FOCUS','ФОКУС'],['Pronto para uma nova sessão.','Ready for a new session.','Готово к новой сессии.'],['Investimentos','Investments','Инвестиции'],['Humor: ótimo','Mood: great','Настроение: отличное'],['Calendário','Calendar','Календарь'],
    ['O custo de continuar no improviso','The cost of staying improvised','Цена жизни без системы'],['Você não precisa perder mais progresso','You do not need to lose more progress','Вам не нужно терять дальнейший прогресс'],['por falta de um sistema.','because you lack a system.','из-за отсутствия системы.'],['SEM LUAR','WITHOUT LUAR','БЕЗ LUAR'],['COM O LUAR','WITH LUAR','С LUAR'],['Você começa.','You start.','Вы начинаете.'],['E perde o ritmo.','And lose momentum.','И теряете ритм.'],['Tudo conectado.','Everything connected.','Всё связано.'],['Progresso preservado.','Progress preserved.','Прогресс сохранён.'],['Esquece contas e compromissos.','Forget bills and appointments.','Забываете счета и встречи.'],['Perde metas de vista.','Lose sight of goals.','Теряете цели из виду.'],['Começa hábitos e para.','Start habits and stop.','Начинаете привычки и бросаете.'],['Usa vários aplicativos separados.','Use several separate apps.','Используете несколько отдельных приложений.'],['Não sabe quanto já economizou.','Do not know how much you have saved.','Не знаете, сколько уже накопили.'],['Tudo em um lugar.','Everything in one place.','Всё в одном месте.'],['Lembretes e agenda conectados.','Connected reminders and calendar.','Связанные напоминания и календарь.'],['Patrimônio e metas visíveis.','Visible assets and goals.','Наглядные активы и цели.'],['Histórico completo da jornada.','Complete journey history.','Полная история пути.'],['Mais clareza para o próximo passo.','More clarity for the next step.','Больше ясности для следующего шага.'],['Criar minha conta grátis →','Create my free account →','Создать бесплатный аккаунт →'],
    ['Experimente a ideia','Try the idea','Попробуйте идею'],['Monte sua primeira órbita.','Build your first orbit.','Создайте свою первую орбиту.'],['Veja o valor antes de decidir.','See the value before deciding.','Оцените пользу до решения.'],['O que faria diferença agora?','What would make a difference now?','Что изменило бы ситуацию сейчас?'],['Rotina','Routine','Режим'],['Dinheiro','Money','Деньги'],['Foco','Focus','Фокус'],['Criar minha órbita grátis →','Create my free orbit →','Создать бесплатную орбиту →'],['Nenhum cartão necessário.','No card required.','Карта не требуется.'],['Quanto várias assinaturas podem custar?','How much can multiple subscriptions cost?','Сколько могут стоить несколько подписок?'],['Gasto mensal estimado','Estimated monthly cost','Ориентировочные расходы в месяц'],['Período da comparação','Comparison period','Период сравнения'],['Outros apps no período','Other apps in the period','Другие приложения за период'],['versus','versus','против'],['LUAR Vitalício','LUAR Lifetime','LUAR Навсегда'],['uma única vez','one time','один раз'],['Desbloquear minha órbita →','Unlock my orbit →','Разблокировать мою орбиту →'],['Pagamento único via Pix · sem renovação · continue grátis se preferir.','One-time Pix payment · no renewal · stay free if you prefer.','Разовая оплата Pix · без продления · при желании оставайтесь на бесплатном плане.'],
    ['DIAGNÓSTICO GRATUITO · MENOS DE 1 MINUTO','FREE DIAGNOSIS · UNDER 1 MINUTE','БЕСПЛАТНАЯ ДИАГНОСТИКА · МЕНЬШЕ 1 МИНУТЫ'],['O que está impedindo','What is holding back','Что мешает'],['sua evolução hoje?','your progress today?','вашему развитию сегодня?'],['Descobrir meu perfil gratuitamente →','Discover my profile for free →','Узнать мой профиль бесплатно →'],['Índice de Organização','Organization Score','Индекс организованности'],['Organização','Organization','Организация'],['Finanças','Finances','Финансы'],['Tudo conectado','Everything connected','Всё связано'],['Uma plataforma completa.','A complete platform.','Полная платформа.'],['Sem perder a tranquilidade.','Without losing peace of mind.','Без потери спокойствия.'],['PLANEJAMENTO FINANCEIRO','FINANCIAL PLANNING','ФИНАНСОВОЕ ПЛАНИРОВАНИЕ'],['Seu dinheiro contado como uma história.','Your money told as a story.','Ваши деньги как понятная история.'],['PRODUTIVIDADE','PRODUCTIVITY','ПРОДУКТИВНОСТЬ'],['Tarefas que fluem.','Tasks that flow.','Задачи без лишних усилий.'],['HÁBITOS','HABITS','ПРИВЫЧКИ'],['Constância visível.','Visible consistency.','Наглядное постоянство.'],['MODO FOCO','FOCUS MODE','РЕЖИМ ФОКУСА'],['Silêncio para avançar.','Quiet to move forward.','Тишина для движения вперёд.'],['BEM-ESTAR','WELL-BEING','БЛАГОПОЛУЧИЕ'],['Entenda seus ciclos.','Understand your cycles.','Понимайте свои циклы.'],['METAS','GOALS','ЦЕЛИ'],['Sonhos com direção.','Dreams with direction.','Мечты с направлением.'],['AGENDA','CALENDAR','КАЛЕНДАРЬ'],['Tempo bem organizado.','Well-organized time.','Хорошо организованное время.'],
    ['Mais de 25 recursos exclusivos','Over 25 exclusive features','Более 25 эксклюзивных функций'],['Tudo o que existe no LUAR.','Everything in LUAR.','Всё, что есть в LUAR.'],['Uma única conta.','One account.','Один аккаунт.'],['Controle financeiro','Financial control','Финансовый контроль'],['Ações e FIIs','Stocks and REIT funds','Акции и фонды недвижимости'],['Criptomoedas','Cryptocurrencies','Криптовалюты'],['Carteira e patrimônio','Portfolio and assets','Портфель и активы'],['Metas financeiras','Financial goals','Финансовые цели'],['Hábitos e streaks','Habits and streaks','Привычки и серии'],['Tarefas e Kanban','Tasks and Kanban','Задачи и Kanban'],['Diário de humor','Mood journal','Дневник настроения'],['Modo foco','Focus mode','Режим фокуса'],['XP e níveis','XP and levels','Опыт и уровни'],['Conquistas','Achievements','Достижения'],['Desafios','Challenges','Испытания'],['Backup na nuvem','Cloud backup','Облачная копия'],['Exportação','Export','Экспорт'],['Importação inteligente','Smart import','Умный импорт'],['Calendário anual','Annual calendar','Годовой календарь'],['Objetivos pessoais','Personal goals','Личные цели'],['Gráficos avançados','Advanced charts','Расширенные графики'],['Evolução financeira','Financial progress','Финансовая динамика'],['Histórico completo','Complete history','Полная история'],['Estatísticas','Statistics','Статистика'],['Perfil personalizado','Custom profile','Персональный профиль'],['Temas exclusivos','Exclusive themes','Эксклюзивные темы'],['Playlists no foco','Focus playlists','Плейлисты для фокуса'],['Relatórios em PDF','PDF reports','Отчёты PDF'],['Sem anúncios','No ads','Без рекламы'],['Atualizações futuras','Future updates','Будущие обновления'],['Desbloquear tudo →','Unlock everything →','Разблокировать всё →'],
    ['Comece sem pagar','Start without paying','Начните бесплатно'],['Experimente primeiro.','Try it first.','Сначала попробуйте.'],['Evolua quando fizer sentido.','Upgrade when it makes sense.','Развивайтесь, когда это уместно.'],['GRATUITO','FREE','БЕСПЛАТНО'],['Ilimitadas','Unlimited','Без ограничений'],['Ilimitados','Unlimited','Без ограничений'],['Datas especiais','Special dates','Особые даты'],['Não incluídas','Not included','Не включены'],['Backup automático','Automatic backup','Автоматическая копия'],['Dashboard e gráficos','Dashboard and charts','Панель и графики'],['Calendário emocional','Mood calendar','Календарь настроения'],['Personalização','Customization','Персонализация'],['Sincronização entre dispositivos','Cross-device sync','Синхронизация устройств'],['Anúncios','Ads','Реклама'],['Nenhum anúncio','No ads','Без рекламы'],['Atualizações','Updates','Обновления'],['Começar gratuitamente','Start for free','Начать бесплатно'],['Quero tudo para sempre →','I want everything forever →','Хочу всё навсегда →'],['Preço especial de lançamento','Special launch price','Специальная цена запуска'],['Sua órbita sem limites.','Your orbit without limits.','Ваша орбита без ограничений.'],['Para sempre.','Forever.','Навсегда.'],['Relatórios e gráficos completos','Complete reports and charts','Полные отчёты и графики'],['Sincronização vitalícia na nuvem','Lifetime cloud sync','Бессрочная облачная синхронизация'],['Experiência sem anúncios','Ad-free experience','Работа без рекламы'],['SEM ANÚNCIOS · SEM MENSALIDADE','NO ADS · NO SUBSCRIPTION','БЕЗ РЕКЛАМЫ · БЕЗ ПОДПИСКИ'],['Pagamento único via Pix','One-time payment via Pix','Разовая оплата через Pix'],['QUERO O LUAR VITALÍCIO ↗','GET LUAR LIFETIME ↗','ХОЧУ LUAR НАВСЕГДА ↗'],
    ['Dúvidas frequentes','Frequently asked questions','Частые вопросы'],['Antes de entrar em órbita.','Before entering orbit.','Перед выходом на орбиту.'],['Preciso pagar para começar?','Do I need to pay to start?','Нужно ли платить, чтобы начать?'],['O Vitalício tem mensalidade?','Does Lifetime have a monthly fee?','Есть ли ежемесячная плата?'],['Quando os recursos são liberados?','When are features unlocked?','Когда открываются функции?'],['Posso fazer backup dos meus dados?','Can I back up my data?','Можно ли создать резервную копию?'],['Como recebo suporte?','How do I get support?','Как получить поддержку?'],['GUIAS PÚBLICOS DO LUAR','PUBLIC LUAR GUIDES','ПУБЛИЧНЫЕ РУКОВОДСТВА LUAR'],['Encontre exatamente o que deseja organizar.','Find exactly what you want to organize.','Найдите именно то, что хотите организовать.'],['Organização pessoal completa','Complete personal organization','Полная личная организация'],['Aplicativo de hábitos','Habit app','Приложение привычек'],['Aplicativo de metas','Goal app','Приложение целей'],['Lista de tarefas online','Online task list','Онлайн-список задач'],['Controle financeiro pessoal','Personal finance control','Управление личными финансами'],['Agenda pessoal online','Online personal calendar','Личный онлайн-календарь'],['Modo foco e timer','Focus mode and timer','Режим фокуса и таймер'],['Aplicativo de notas','Notes app','Приложение заметок'],['Controle de investimentos','Investment tracking','Учёт инвестиций'],['Backup e sincronização','Backup and sync','Резервное копирование и синхронизация'],['Estatísticas de produtividade','Productivity statistics','Статистика продуктивности'],['TUDO O QUE VOCÊ PRECISA. PARA SEMPRE.','EVERYTHING YOU NEED. FOREVER.','ВСЁ, ЧТО ВАМ НУЖНО. НАВСЕГДА.'],['Uma vida organizada.','An organized life.','Организованная жизнь.'],['Sem voltar ao caos.','Without returning to chaos.','Без возврата к хаосу.'],['Sem mensalidade.','No monthly fee.','Без ежемесячной платы.'],['Sem limites.','No limits.','Без ограничений.'],['Sem renovação.','No renewal.','Без продления.'],['Prefiro começar gratuitamente →','I prefer to start for free →','Я предпочитаю начать бесплатно →'],
    ['ORGANIZAÇÃO','ORGANIZATION','ОРГАНИЗАЦИЯ'],['BEM-ESTAR','WELL-BEING','БЛАГОПОЛУЧИЕ'],['EVOLUÇÃO','PROGRESS','РАЗВИТИЕ'],['Relatórios','Reports','Отчёты'],['Perfil','Profile','Профиль'],['Configurações','Settings','Настройки'],['Buscar tarefas, hábitos, agenda, metas...','Search tasks, habits, calendar, goals...','Поиск задач, привычек, календаря, целей...'],['Notificações','Notifications','Уведомления'],['Ir para o perfil','Go to profile','Перейти в профиль'],['Conta, aparência e evolução','Account, appearance and progress','Аккаунт, внешний вид и прогресс'],['Sair da conta','Sign out','Выйти'],['Encerrar esta sessão','End this session','Завершить сеанс'],['HOJE','TODAY','СЕГОДНЯ'],['Boa noite','Good evening','Добрый вечер'],['Boa tarde','Good afternoon','Добрый день'],['Bom dia','Good morning','Доброе утро'],['viajante','traveler','путешественник'],['Comece sua jornada. Cada pequeno passo conta.','Start your journey. Every small step counts.','Начните свой путь. Каждый маленький шаг важен.'],['Adicionar registro','Add entry','Добавить запись'],['Patrimônio total','Total assets','Общие активы'],['Comece hoje','Start today','Начните сегодня'],['Sem movimentações','No transactions','Нет операций'],['Guardado em metas','Saved in goals','Накоплено на цели'],['Saldo disponível','Available balance','Доступный баланс'],['Todo o histórico','Full history','Вся история'],['PLANEJAMENTO DO MÊS','MONTHLY PLANNING','ПЛАН НА МЕСЯЦ'],['Seu orçamento em órbita','Your budget in orbit','Ваш бюджет на орбите'],['Ver detalhes →','View details →','Подробнее →'],['Disponível após gastos','Available after expenses','Доступно после расходов'],['Recebimentos','Income','Поступления'],['Gastos','Expenses','Расходы'],['Compras','Purchases','Покупки'],['Seu dia em órbita','Your day in orbit','Ваш день на орбите'],['Ver tudo →','View all →','Смотреть всё →'],['Sua órbita começa aqui','Your orbit starts here','Ваша орбита начинается здесь'],['Nenhuma atividade para hoje','No activity for today','Сегодня нет активности'],['Crie sua primeira tarefa ou hábito.','Create your first task or habit.','Создайте первую задачу или привычку.'],['Adicionar nova tarefa','Add new task','Добавить задачу'],['Suas metas aparecerão aqui','Your goals will appear here','Ваши цели появятся здесь'],['Nova meta','New goal','Новая цель'],['Recorrências sob controle','Recurring payments under control','Регулярные платежи под контролем'],['Nenhuma assinatura','No subscriptions','Нет подписок'],['Iniciar sessão','Start session','Начать сессию'],['Sua sequência atual','Your current streak','Ваша текущая серия'],['Conclua todos os hábitos de hoje para começar.','Complete all of today’s habits to begin.','Выполните все привычки на сегодня, чтобы начать.'],['Abrir agenda →','Open calendar →','Открыть календарь →'],
    ['CONTROLE FINANCEIRO','FINANCIAL CONTROL','ФИНАНСОВЫЙ КОНТРОЛЬ'],['Seu dinheiro, com clareza.','Your money, clearly.','Ваши деньги, понятно.'],['Acompanhe entradas, saídas e o ritmo da sua vida financeira.','Track income, expenses and the rhythm of your financial life.','Следите за доходами, расходами и ритмом финансовой жизни.'],['Novo lançamento','New transaction','Новая операция'],['Gastos e compras do mês','Monthly expenses and purchases','Расходы и покупки за месяц'],['Saldo disponível no mês','Available monthly balance','Доступный остаток за месяц'],['EVOLUÇÃO FINANCEIRA','FINANCIAL PROGRESS','ФИНАНСОВАЯ ДИНАМИКА'],['Para onde seu dinheiro está indo','Where your money is going','Куда уходят ваши деньги'],['Patrimônio total','Total assets','Общие активы'],['Todas as linhas','All lines','Все линии'],['● Patrimônio','● Assets','● Активы'],['● Ganhos','● Income','● Доходы'],['● Gastos','● Expenses','● Расходы'],['● Compras','● Purchases','● Покупки'],['● Total investido','● Total invested','● Всего инвестировано'],['HISTÓRICO','HISTORY','ИСТОРИЯ'],['Seus lançamentos','Your transactions','Ваши операции'],['Filtrar','Filter','Фильтр'],['Nenhum lançamento','No transactions','Нет операций'],['Registre um ganho ou gasto para começar.','Record income or an expense to begin.','Добавьте доход или расход, чтобы начать.'],['QUERO COMPRAR','I WANT TO BUY','ХОЧУ КУПИТЬ'],['Compre com intenção','Buy intentionally','Покупайте осознанно'],
    ['Nova tarefa','New task','Новая задача'],['A FAZER','TO DO','СДЕЛАТЬ'],['EM PROGRESSO','IN PROGRESS','В ПРОЦЕССЕ'],['CONCLUÍDAS','COMPLETED','ЗАВЕРШЕНО'],['Nenhuma tarefa','No tasks','Нет задач'],['Crie sua primeira tarefa.','Create your first task.','Создайте первую задачу.'],['SEU MOMENTO','YOUR MOMENT','ВАШ МОМЕНТ'],['Entre em órbita.','Enter orbit.','Выйдите на орбиту.'],['Silencie o mundo por alguns minutos.','Silence the world for a few minutes.','Отключитесь от мира на несколько минут.'],['Personalizado','Custom','Свой режим'],['Usar minutos','Use minutes','Использовать минуты'],['Ambiente','Ambience','Фоновый звук'],['Chuva','Rain','Дождь'],['Floresta','Forest','Лес'],['Ruído branco','White noise','Белый шум'],['Escolha um som para acompanhar sua sessão.','Choose a sound for your session.','Выберите звук для сессии.'],['PLAYLIST PERSONALIZADA','CUSTOM PLAYLIST','СВОЙ ПЛЕЙЛИСТ'],['Tocar','Play','Включить'],['CRONÔMETRO DE FOCO','FOCUS STOPWATCH','СЕКУНДОМЕР ФОКУСА'],['Foque sem definir um limite.','Focus without setting a limit.','Фокусируйтесь без ограничения времени.'],['Habilitar cronômetro','Enable stopwatch','Включить секундомер'],['Hoje','Today','Сегодня'],['Esta semana','This week','Эта неделя'],['Este mês','This month','Этот месяц'],
    ['PERSONALIZAÇÃO E DADOS','CUSTOMIZATION AND DATA','ПЕРСОНАЛИЗАЦИЯ И ДАННЫЕ'],['Conta, aparência, dados e informações do LUAR em áreas organizadas.','Account, appearance, data and LUAR information in organized areas.','Аккаунт, внешний вид, данные и информация LUAR в понятных разделах.'],['CONTA E APARÊNCIA','ACCOUNT AND APPEARANCE','АККАУНТ И ВНЕШНИЙ ВИД'],['Seu LUAR, do seu jeito','Your LUAR, your way','Ваш LUAR по-вашему'],['DADOS E SEGURANÇA','DATA AND SECURITY','ДАННЫЕ И БЕЗОПАСНОСТЬ'],['Proteção e controle','Protection and control','Защита и контроль'],['SOBRE O LUAR','ABOUT LUAR','О LUAR'],['Projeto e suporte','Project and support','Проект и поддержка'],['REINÍCIO','RESET','СБРОС'],['Ações importantes','Important actions','Важные действия'],['APARÊNCIA','APPEARANCE','ВНЕШНИЙ ВИД'],['Escolha a identidade da sua órbita','Choose your orbit identity','Выберите стиль своей орбиты'],['Movimento da interface','Interface motion','Анимация интерфейса'],['Desativar animações','Disable animations','Отключить анимацию'],['BACKUP E RESTAURAÇÃO','BACKUP AND RESTORE','РЕЗЕРВНОЕ КОПИРОВАНИЕ'],['Leve sua órbita com você','Take your orbit with you','Возьмите свою орбиту с собой'],['Exportar backup','Export backup','Экспорт копии'],['Importar backup','Import backup','Импорт копии'],['ARMAZENAMENTO','STORAGE','ХРАНИЛИЩЕ'],['Seus dados nesta instalação','Your data in this installation','Ваши данные в этой установке'],['ZONA DE REINÍCIO','RESET ZONE','ЗОНА СБРОСА'],['Recomeçar do zero','Start over','Начать заново'],['Apagar todos os meus dados','Delete all my data','Удалить все мои данные'],['Termos de Uso','Terms of Use','Условия использования'],['Privacidade','Privacy','Конфиденциальность'],['Cookies','Cookies','Файлы cookie'],['Contato','Contact','Контакты'],
    ['Meu dia','My day','Мой день'],['Modo foco','Focus mode','Режим фокуса'],['Humor','Mood','Настроение'],['Notas','Notes','Заметки'],['Desafios','Challenges','Испытания'],['Relatórios','Reports','Отчёты'],['Perfil','Profile','Профиль'],['Configurações','Settings','Настройки'],['Sair da conta','Sign out','Выйти'],['Ir para o perfil','Go to profile','Перейти в профиль'],
    ['PUBLICIDADE','ADVERTISING','РЕКЛАМА'],['Conteúdo patrocinado','Sponsored content','Спонсорский контент'],['Espaço reservado','Reserved space','Рекламное место'],['Nenhuma campanha disponível','No campaign available','Нет доступной кампании'],['LUAR GRATUITO','LUAR FREE','LUAR БЕСПЛАТНО'],['Para remover os anúncios,','To remove ads,','Чтобы убрать рекламу,'],['desbloqueie o LUAR Vitalício.','unlock LUAR Lifetime.','разблокируйте LUAR Навсегда.'],['Feito!','Done!','Готово!'],['Seu progresso foi salvo.','Your progress has been saved.','Ваш прогресс сохранён.']
  ];

  const dictionaries = { en: new Map(), ru: new Map() };
  ENTRIES.forEach(([pt,en,ru]) => { dictionaries.en.set(pt,en); dictionaries.ru.set(pt,ru); });
  const originalText = new WeakMap();
  const originalAttributes = new WeakMap();
  let currentLanguage = normalize(localStorage.getItem(STORAGE_KEY)) || 'pt';
  let scheduled = false;

  function normalize(code) { return Object.hasOwn(LANGUAGES, String(code || '').toLowerCase()) ? String(code).toLowerCase() : ''; }
  function languageInfo(code = currentLanguage) { return LANGUAGES[normalize(code) || 'pt']; }
  function exact(value, code = currentLanguage) { if (code === 'pt') return value; return dictionaries[code]?.get(value) || pattern(value, code) || value; }
  function pattern(value, code) {
    let match;
    if ((match = value.match(/^Nível (\d+)$/))) return code === 'en' ? `Level ${match[1]}` : `Уровень ${match[1]}`;
    if ((match = value.match(/^(\d+) XP para o próximo nível$/))) return code === 'en' ? `${match[1]} XP to the next level` : `${match[1]} XP до следующего уровня`;
    if ((match = value.match(/^Passo (\d+) de (\d+)$/))) return code === 'en' ? `Step ${match[1]} of ${match[2]}` : `Шаг ${match[1]} из ${match[2]}`;
    if ((match = value.match(/^(\d+) dias$/))) return code === 'en' ? `${match[1]} days` : `${match[1]} дн.`;
    if ((match = value.match(/^(\d+) de (\d+) atividades concluídas$/))) return code === 'en' ? `${match[1]} of ${match[2]} activities completed` : `${match[1]} из ${match[2]} активностей выполнено`;
    if ((match = value.match(/^(\d+) de (\d+) hábitos hoje$/))) return code === 'en' ? `${match[1]} of ${match[2]} habits today` : `${match[1]} из ${match[2]} привычек сегодня`;
    if ((match = value.match(/^Gratuito: (.+)$/))) return code === 'en' ? `Free: ${match[1]}` : `Бесплатно: ${match[1]}`;
    return '';
  }
  function ignored(node) { const element = node.nodeType === Node.ELEMENT_NODE ? node : node.parentElement; return !element || !!element.closest('script,style,code,pre,[data-no-translate]'); }
  function translatedNodeValue(original) {
    const leading = original.match(/^\s*/)?.[0] || '';
    const trailing = original.match(/\s*$/)?.[0] || '';
    const core = original.trim();
    return core ? `${leading}${exact(core)}${trailing}` : original;
  }
  function applyTextNode(node, refreshOriginal = false) {
    if (ignored(node)) return;
    const known = originalText.get(node);
    const expected = known === undefined ? '' : translatedNodeValue(known);
    if (refreshOriginal && known !== undefined && node.nodeValue !== expected) originalText.set(node,node.nodeValue);
    if (!originalText.has(node)) originalText.set(node,node.nodeValue);
    const translated = translatedNodeValue(originalText.get(node));
    if (node.nodeValue !== translated) node.nodeValue = translated;
  }
  function applyAttributes(element, refreshOriginal = false) {
    if (ignored(element)) return;
    const names = ['placeholder','title','aria-label'];
    let originals = originalAttributes.get(element);
    if (!originals) { originals = new Map(); originalAttributes.set(element,originals); }
    names.forEach(name => {
      if (!element.hasAttribute(name)) return;
      const current = element.getAttribute(name);
      const known = originals.get(name);
      const expected = known === undefined ? '' : exact(known);
      if (refreshOriginal && known !== undefined && current !== expected) originals.set(name,current);
      if (!originals.has(name)) originals.set(name,current);
      const translated = exact(originals.get(name));
      if (current !== translated) element.setAttribute(name,translated);
    });
  }
  function translateTree(root = document.body) {
    if (!root) return;
    if (root.nodeType === Node.TEXT_NODE) { applyTextNode(root); return; }
    if (root.nodeType !== Node.ELEMENT_NODE && root.nodeType !== Node.DOCUMENT_FRAGMENT_NODE) return;
    if (root.nodeType === Node.ELEMENT_NODE) applyAttributes(root);
    const walker = document.createTreeWalker(root,NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_TEXT);
    let node;
    while ((node = walker.nextNode())) node.nodeType === Node.TEXT_NODE ? applyTextNode(node) : applyAttributes(node);
  }
  function controlMarkup(kind) {
    if (kind === 'landing') return `<label class="landing-language-select" data-no-translate><span data-language-flag>${languageInfo().flag}</span><select data-language-select aria-label="Idioma do site"><option value="pt">Português</option><option value="en">English</option><option value="ru">Русский</option></select></label>`;
    return `<article class="card settings-card language-settings-card" data-language-rendered="${currentLanguage}" data-no-translate><span>${currentLanguage === 'en' ? 'LANGUAGE' : currentLanguage === 'ru' ? 'ЯЗЫК' : 'IDIOMA'}</span><h3>${currentLanguage === 'en' ? 'Choose the site language' : currentLanguage === 'ru' ? 'Выберите язык сайта' : 'Escolha o idioma do site'}</h3><p>${currentLanguage === 'en' ? 'The choice applies to the landing page and your logged-in interface.' : currentLanguage === 'ru' ? 'Выбор применяется к лендингу и интерфейсу после входа.' : 'A escolha vale para a landing page e para sua interface após o login.'}</p><div class="settings-language-options">${Object.entries(LANGUAGES).map(([code,item])=>`<button type="button" data-language="${code}" aria-pressed="${currentLanguage===code}"><i>${item.flag}</i><b>${item.nativeName}<small>${item.country}</small></b><em>${currentLanguage===code?'✓':''}</em></button>`).join('')}</div></article>`;
  }
  function ensureControls() {
    const nav = document.querySelector('.landing-nav');
    if (nav && !nav.querySelector('[data-language-select]')) nav.querySelector('.landing-nav-actions,.landing-profile')?.insertAdjacentHTML('beforebegin',controlMarkup('landing'));
    const grid = document.getElementById('settingsAccountGrid');
    if (grid && !grid.querySelector('.language-settings-card')) grid.insertAdjacentHTML('beforeend',controlMarkup('settings'));
    document.querySelectorAll('[data-language-select]').forEach(select => { if (select.value !== currentLanguage) select.value = currentLanguage; const flag=select.closest('.landing-language-select')?.querySelector('[data-language-flag]'); if(flag)flag.textContent=languageInfo().flag; });
    document.querySelectorAll('[data-language]').forEach(button => { const active=button.dataset.language===currentLanguage; button.setAttribute('aria-pressed',String(active)); const mark=button.querySelector('em'); if(mark)mark.textContent=active?'✓':''; });
    const card = document.querySelector('.language-settings-card');
    if (card && card.dataset.languageRendered !== currentLanguage) { const fresh=document.createElement('div'); fresh.innerHTML=controlMarkup('settings'); card.replaceWith(fresh.firstElementChild); }
  }
  function syncAccountPreference() {
    try {
      if (typeof state === 'undefined' || !state?.profile) return;
      const accountLanguage = normalize(state.profile.language);
      if (document.body.classList.contains('app-mode') && accountLanguage && accountLanguage !== currentLanguage) { setLanguage(accountLanguage,{ persist:true, syncAccount:false }); return; }
      if (document.body.classList.contains('app-mode') && !accountLanguage) {
        state.profile.language=currentLanguage;
        if (typeof writeLocalState === 'function') writeLocalState();
        if (typeof scheduleCloudSave === 'function') scheduleCloudSave();
      }
    } catch {}
  }
  function persistAccountPreference(code) {
    try {
      if (typeof state === 'undefined' || !state?.profile) return;
      state.profile.language=code;
      if (typeof writeLocalState === 'function') writeLocalState();
      if (typeof currentUser !== 'undefined' && currentUser && typeof scheduleCloudSave === 'function') scheduleCloudSave();
    } catch {}
  }
  function setLanguage(code, options = {}) {
    code = normalize(code) || 'pt';
    const persist = options.persist !== false;
    const syncAccount = options.syncAccount !== false;
    currentLanguage=code;
    if (persist) localStorage.setItem(STORAGE_KEY,code);
    document.documentElement.lang=languageInfo().locale;
    document.documentElement.dataset.language=code;
    translateTree(document.body);
    ensureControls();
    if (syncAccount) persistAccountPreference(code);
    window.dispatchEvent(new CustomEvent('luar:languagechange',{detail:{code,locale:languageInfo().locale}}));
  }
  function scheduleRefresh() {
    if (scheduled) return;
    scheduled=true;
    requestAnimationFrame(()=>{scheduled=false;translateTree(document.body);ensureControls();syncAccountPreference()});
  }

  document.addEventListener('change',event=>{const select=event.target.closest('[data-language-select]');if(select)setLanguage(select.value)});
  document.addEventListener('click',event=>{const button=event.target.closest('[data-language]');if(button)setLanguage(button.dataset.language)});
  const observer = new MutationObserver(records => {
    records.forEach(record => {
      if (record.type === 'characterData') applyTextNode(record.target,true);
      if (record.type === 'attributes') applyAttributes(record.target,true);
      if (record.type === 'childList') record.addedNodes.forEach(node=>translateTree(node));
    });
    scheduleRefresh();
  });
  observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['placeholder','title','aria-label','class']});

  window.LuarLanguage = Object.freeze({
    set: setLanguage,
    current: () => currentLanguage,
    locale: () => languageInfo().locale,
    info: code => ({ ...languageInfo(code) }),
    translate: value => exact(String(value ?? '')),
    languages: () => Object.entries(LANGUAGES).map(([code,item])=>({code,...item}))
  });
  setLanguage(normalize(typeof state !== 'undefined' ? state?.profile?.language : '') || currentLanguage,{persist:true,syncAccount:false});
})();
