begin;

create table if not exists public.luar_accounts (
  email text primary key check (email = lower(btrim(email))),
  user_ids uuid[] not null default '{}',
  plan text not null default 'free' check (plan in ('free', 'lifetime')),
  lifetime_paid_at timestamptz,
  lifetime_transaction_id text unique,
  lifetime_source text not null default 'none',
  lifetime_provider text,
  lifetime_granted_by uuid,
  lifetime_granted_at timestamptz,
  lifetime_revoked_at timestamptz,
  state jsonb not null default '{}'::jsonb,
  state_updated_at timestamptz,
  backups jsonb not null default '[]'::jsonb check (jsonb_typeof(backups) = 'array'),
  login_count integer not null default 0 check (login_count >= 0),
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.luar_accounts add column if not exists lifetime_source text not null default 'none';
alter table public.luar_accounts add column if not exists lifetime_provider text;
alter table public.luar_accounts add column if not exists lifetime_granted_by uuid;
alter table public.luar_accounts add column if not exists lifetime_granted_at timestamptz;
alter table public.luar_accounts add column if not exists lifetime_revoked_at timestamptz;

do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'luar_accounts' and column_name = 'login_count'
  ) then
    alter table public.luar_accounts add column login_count integer not null default 0 check (login_count >= 0);
    alter table public.luar_accounts add column last_login_at timestamptz;
    update public.luar_accounts set login_count = 1 where login_count = 0;
  elsif not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'luar_accounts' and column_name = 'last_login_at'
  ) then
    alter table public.luar_accounts add column last_login_at timestamptz;
  end if;
end $$;

create or replace function public.record_luar_login(p_email text, p_user_id uuid)
returns table(login_count integer, first_login boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text := lower(btrim(coalesce(p_email, '')));
  v_count integer;
begin
  if v_email = '' or p_user_id is null then
    raise exception 'INVALID_LOGIN_EVENT';
  end if;

  insert into public.luar_accounts (email, user_ids, login_count, last_login_at)
  values (v_email, array[p_user_id], 1, now())
  on conflict (email) do update set
    user_ids = (
      select array_agg(distinct linked_id)
      from unnest(public.luar_accounts.user_ids || excluded.user_ids) linked_id
    ),
    login_count = public.luar_accounts.login_count + 1,
    last_login_at = now(),
    updated_at = now()
  returning public.luar_accounts.login_count into v_count;

  return query select v_count, v_count = 1;
end;
$$;

revoke all on function public.record_luar_login(text, uuid) from public, anon, authenticated;
grant execute on function public.record_luar_login(text, uuid) to service_role;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'luar_accounts_lifetime_source_check'
      and conrelid = 'public.luar_accounts'::regclass
  ) then
    alter table public.luar_accounts
      add constraint luar_accounts_lifetime_source_check
      check (lifetime_source in ('none', 'purchase', 'legacy', 'bootstrap', 'admin', 'referral'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'luar_accounts_lifetime_provider_check'
      and conrelid = 'public.luar_accounts'::regclass
  ) then
    alter table public.luar_accounts
      add constraint luar_accounts_lifetime_provider_check
      check (lifetime_provider is null or lifetime_provider in ('google', 'discord', 'email'));
  end if;
end
$$;

create table if not exists public.luar_payments (
  transaction_id text primary key,
  account_email text not null references public.luar_accounts(email) on update cascade on delete restrict,
  user_id uuid not null references auth.users(id) on delete restrict,
  amount_cents integer not null check (amount_cents > 0),
  status text not null default 'created',
  created_at timestamptz not null default now(),
  paid_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists luar_payments_account_email_idx on public.luar_payments(account_email);

create table if not exists public.luar_lifetime_admin_audit (
  id bigint generated by default as identity primary key,
  actor_user_id uuid not null,
  actor_email text not null,
  target_email text not null,
  target_provider text not null check (target_provider in ('google', 'discord', 'email')),
  action text not null check (action in ('grant', 'revoke')),
  previous_plan text not null,
  previous_source text not null,
  new_plan text not null,
  new_source text not null,
  created_at timestamptz not null default now()
);

create index if not exists luar_lifetime_admin_audit_target_idx
on public.luar_lifetime_admin_audit(target_email, created_at desc);

alter table public.luar_accounts enable row level security;
alter table public.luar_payments enable row level security;
alter table public.luar_lifetime_admin_audit enable row level security;
revoke all on public.luar_accounts from anon, authenticated;
revoke all on public.luar_payments from anon, authenticated;
revoke all on public.luar_lifetime_admin_audit from anon, authenticated;
revoke all on sequence public.luar_lifetime_admin_audit_id_seq from anon, authenticated;

update public.luar_accounts
set lifetime_source = case
  when email = 'msgdo.2007@gmail.com' then 'bootstrap'
  when lifetime_transaction_id is not null then 'purchase'
  else 'legacy'
end
where plan = 'lifetime' and lifetime_source = 'none';

create or replace function public.preserve_luar_lifetime()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.plan = 'lifetime' and coalesce(new.lifetime_source, 'none') = 'none' then
    new.lifetime_source := case
      when new.email = 'msgdo.2007@gmail.com' then 'bootstrap'
      when new.lifetime_transaction_id is not null then 'purchase'
      else 'legacy'
    end;
  end if;

  -- Compras, licenças antigas e a conta bootstrap nunca podem ser rebaixadas.
  if old.plan = 'lifetime' and coalesce(old.lifetime_source, 'none') <> 'admin' then
    new.plan := 'lifetime';
    new.lifetime_paid_at := coalesce(old.lifetime_paid_at, new.lifetime_paid_at);
    new.lifetime_transaction_id := coalesce(old.lifetime_transaction_id, new.lifetime_transaction_id);
    new.lifetime_source := case
      when coalesce(old.lifetime_source, 'none') = 'none' then 'legacy'
      else old.lifetime_source
    end;
    new.lifetime_provider := coalesce(old.lifetime_provider, new.lifetime_provider);
    new.lifetime_granted_by := coalesce(old.lifetime_granted_by, new.lifetime_granted_by);
    new.lifetime_granted_at := coalesce(old.lifetime_granted_at, new.lifetime_granted_at);
    new.lifetime_revoked_at := old.lifetime_revoked_at;
  elsif old.plan = 'lifetime' and old.lifetime_source = 'admin' and new.plan <> 'lifetime' then
    if coalesce(current_setting('luar.admin_revoke', true), '') <> '1' then
      new.plan := 'lifetime';
      new.lifetime_paid_at := coalesce(old.lifetime_paid_at, new.lifetime_paid_at);
      new.lifetime_transaction_id := coalesce(old.lifetime_transaction_id, new.lifetime_transaction_id);
      new.lifetime_source := 'admin';
      new.lifetime_provider := old.lifetime_provider;
      new.lifetime_granted_by := old.lifetime_granted_by;
      new.lifetime_granted_at := old.lifetime_granted_at;
      new.lifetime_revoked_at := old.lifetime_revoked_at;
    else
      new.plan := 'free';
      new.lifetime_paid_at := null;
      new.lifetime_transaction_id := null;
      new.lifetime_source := 'none';
      new.lifetime_provider := null;
      new.lifetime_granted_by := null;
      new.lifetime_granted_at := null;
      new.lifetime_revoked_at := coalesce(new.lifetime_revoked_at, now());
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists preserve_luar_lifetime_trigger on public.luar_accounts;
create trigger preserve_luar_lifetime_trigger
before update on public.luar_accounts
for each row execute function public.preserve_luar_lifetime();

create or replace function public.admin_manage_luar_lifetime(
  p_action text,
  p_target_email text,
  p_provider text
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_actor_id uuid := auth.uid();
  v_actor_email text;
  v_auth_method text;
  v_auth_at bigint;
  v_identity_provider text;
  v_identity_at bigint;
  v_target_email text := lower(btrim(coalesce(p_target_email, '')));
  v_action text := lower(btrim(coalesce(p_action, '')));
  v_provider text := lower(btrim(coalesce(p_provider, '')));
  v_previous_plan text;
  v_previous_source text;
  v_previous_provider text;
  v_new_plan text;
  v_new_source text;
  v_new_provider text;
  v_changed boolean := false;
begin
  select lower(btrim(u.email))
  into v_actor_email
  from auth.users u
  where u.id = v_actor_id
    and u.email_confirmed_at is not null;

  select lower(entry->>'method'), coalesce((entry->>'timestamp')::bigint, 0)
  into v_auth_method, v_auth_at
  from jsonb_array_elements(coalesce(auth.jwt()->'amr', '[]'::jsonb)) entry
  order by coalesce((entry->>'timestamp')::bigint, 0) desc
  limit 1;

  select lower(i.provider), coalesce(extract(epoch from i.last_sign_in_at)::bigint, 0)
  into v_identity_provider, v_identity_at
  from auth.identities i
  where i.user_id = v_actor_id
  order by i.last_sign_in_at desc nulls last, i.updated_at desc nulls last, i.created_at desc
  limit 1;

  if v_actor_email is distinct from 'msgdo.2007@gmail.com'
     or coalesce(v_auth_method, '') <> 'oauth'
     or coalesce(v_identity_provider, '') <> 'google'
     or coalesce(v_auth_at, 0) = 0
     or coalesce(v_identity_at, 0) = 0
     or abs(v_identity_at - v_auth_at) > 300 then
    raise exception 'ADMIN_FORBIDDEN' using errcode = '42501';
  end if;

  if v_action not in ('grant', 'revoke')
     or v_provider not in ('google', 'discord', 'email')
     or char_length(v_target_email) > 254
     or v_target_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    raise exception 'TARGET_INVALID' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(v_target_email, 0));

  select a.plan, coalesce(a.lifetime_source, 'none'), a.lifetime_provider
  into v_previous_plan, v_previous_source, v_previous_provider
  from public.luar_accounts a
  where a.email = v_target_email
  for update;

  if not found then
    v_previous_plan := 'free';
    v_previous_source := 'none';
    v_previous_provider := null;
  end if;

  if v_action = 'grant' then
    if v_previous_plan = 'lifetime' and v_previous_source <> 'admin' then
      v_new_plan := v_previous_plan;
      v_new_source := v_previous_source;
      v_new_provider := coalesce(v_previous_provider, v_provider);
    elsif v_previous_plan = 'lifetime' then
      update public.luar_accounts
      set lifetime_provider = v_provider,
          lifetime_granted_by = coalesce(lifetime_granted_by, v_actor_id),
          lifetime_granted_at = coalesce(lifetime_granted_at, now()),
          lifetime_revoked_at = null,
          updated_at = now()
      where email = v_target_email;
      v_new_plan := 'lifetime';
      v_new_source := 'admin';
      v_new_provider := v_provider;
      v_changed := v_previous_provider is distinct from v_provider;
    else
      insert into public.luar_accounts (
        email, plan, lifetime_paid_at, lifetime_source, lifetime_provider,
        lifetime_granted_by, lifetime_granted_at, lifetime_revoked_at, updated_at
      ) values (
        v_target_email, 'lifetime', now(), 'admin', v_provider,
        v_actor_id, now(), null, now()
      )
      on conflict (email) do update set
        plan = 'lifetime',
        lifetime_paid_at = coalesce(public.luar_accounts.lifetime_paid_at, excluded.lifetime_paid_at),
        lifetime_source = 'admin',
        lifetime_provider = excluded.lifetime_provider,
        lifetime_granted_by = excluded.lifetime_granted_by,
        lifetime_granted_at = excluded.lifetime_granted_at,
        lifetime_revoked_at = null,
        updated_at = now();
      v_new_plan := 'lifetime';
      v_new_source := 'admin';
      v_new_provider := v_provider;
      v_changed := true;
    end if;
  else
    if v_previous_plan = 'lifetime' and v_previous_source <> 'admin' then
      raise exception 'PERMANENT_LIFETIME' using errcode = 'P0001';
    end if;
    if v_previous_plan = 'lifetime'
       and v_previous_provider is not null
       and v_previous_provider <> v_provider then
      raise exception 'PROVIDER_MISMATCH' using errcode = 'P0001';
    end if;
    if v_previous_plan = 'lifetime' then
      perform set_config('luar.admin_revoke', '1', true);
      update public.luar_accounts
      set plan = 'free',
          lifetime_paid_at = null,
          lifetime_transaction_id = null,
          lifetime_source = 'none',
          lifetime_provider = null,
          lifetime_granted_by = null,
          lifetime_granted_at = null,
          lifetime_revoked_at = now(),
          updated_at = now()
      where email = v_target_email;
      v_changed := true;
    end if;
    v_new_plan := 'free';
    v_new_source := 'none';
    v_new_provider := v_provider;
  end if;

  -- Registra e devolve o estado realmente persistido, inclusive sob concorrência.
  select a.plan, coalesce(a.lifetime_source, 'none'), a.lifetime_provider
  into v_new_plan, v_new_source, v_new_provider
  from public.luar_accounts a
  where a.email = v_target_email;
  if not found then
    v_new_plan := 'free';
    v_new_source := 'none';
    v_new_provider := v_provider;
  end if;
  v_changed := v_previous_plan is distinct from v_new_plan
    or v_previous_source is distinct from v_new_source
    or (v_new_source = 'admin' and v_previous_provider is distinct from v_new_provider);

  insert into public.luar_lifetime_admin_audit (
    actor_user_id, actor_email, target_email, target_provider, action,
    previous_plan, previous_source, new_plan, new_source
  ) values (
    v_actor_id, v_actor_email, v_target_email, v_provider, v_action,
    v_previous_plan, v_previous_source, v_new_plan, v_new_source
  );

  return jsonb_build_object(
    'email', v_target_email,
    'provider', coalesce(v_new_provider, v_provider),
    'action', v_action,
    'lifetime', v_new_plan = 'lifetime',
    'source', v_new_source,
    'changed', v_changed
  );
end;
$$;

revoke all on function public.admin_manage_luar_lifetime(text, text, text) from public, anon;
grant execute on function public.admin_manage_luar_lifetime(text, text, text) to authenticated;

insert into public.luar_accounts (email, user_ids, state, state_updated_at, backups)
select lower(btrim(email)), array_agg(id order by created_at),
       coalesce((array_agg(raw_user_meta_data->'luar_state' order by updated_at desc)
         filter (where jsonb_typeof(raw_user_meta_data->'luar_state') = 'object'))[1], '{}'::jsonb),
       max(nullif(raw_user_meta_data->>'luar_updated_at', '')::timestamptz),
       coalesce((array_agg(raw_user_meta_data->'luar_backups' order by updated_at desc)
         filter (where jsonb_typeof(raw_user_meta_data->'luar_backups') = 'array'))[1], '[]'::jsonb)
from auth.users
where email is not null and btrim(email) <> ''
group by lower(btrim(email))
on conflict (email) do update set
  user_ids = (select array_agg(distinct value) from unnest(public.luar_accounts.user_ids || excluded.user_ids) value),
  state = case
    when excluded.state_updated_at is not null
         and (public.luar_accounts.state_updated_at is null
              or excluded.state_updated_at > public.luar_accounts.state_updated_at)
      then excluded.state
    when excluded.state_updated_at is null
         and public.luar_accounts.state_updated_at is null
         and public.luar_accounts.state = '{}'::jsonb
         and excluded.state <> '{}'::jsonb
      then excluded.state
    else public.luar_accounts.state
  end,
  state_updated_at = greatest(public.luar_accounts.state_updated_at, excluded.state_updated_at),
  backups = (
    select coalesce(jsonb_agg(item), '[]'::jsonb)
    from (
      select distinct item
      from jsonb_array_elements(public.luar_accounts.backups || excluded.backups) as merged(item)
    ) preserved
  ),
  updated_at = now();

-- Compra confirmada antes da adoção deste armazenamento durável.
update public.luar_accounts
set plan = 'lifetime', lifetime_paid_at = coalesce(lifetime_paid_at, now()), updated_at = now()
where email = 'msgdo.2007@gmail.com';

-- O estado e os backups antigos já estão em luar_accounts. Removê-los do JWT
-- evita cabeçalhos de autenticação grandes demais para Vercel e navegadores.
update auth.users
set raw_user_meta_data = coalesce(raw_user_meta_data, '{}'::jsonb) - 'luar_state' - 'luar_backups',
    updated_at = now()
where raw_user_meta_data ? 'luar_state' or raw_user_meta_data ? 'luar_backups';

notify pgrst, 'reload schema';

commit;
