(() => {
  const MODES = { free: "Livre", earth: "Planeta", brain: "Cérebro", blackhole: "Buraco negro" };
  const LINK_TYPES = { related: "Relacionada", "created-from": "Nasceu de", "depends-on": "Depende de", "part-of": "Parte de" };
  let root, canvas, ctx, detail, search, typeFilter, categoryFilter, selectedId = "", hoverId = "";
  let nodes = [], links = [], categories = [], raf = 0, running = false, alpha = 0, last = 0;
  let mainResizeObserver = null, miniResizeObserver = null;
  let camera = { x: 0, y: 0, zoom: 1 }, gesture = null, pointers = new Map(), longPress = 0, selectionInitialized = false;

  const notes = () => Array.isArray(state.notes) ? state.notes : [];
  const config = () => {
    state.profile ||= {};
    const value = state.profile.ideaMap && typeof state.profile.ideaMap === "object" ? state.profile.ideaMap : {};
    value.theme = MODES[value.theme] ? value.theme : "free";
    value.selectedCategory = String(value.selectedCategory || "all");
    value.connections = Array.isArray(value.connections) ? value.connections : [];
    value.positions = value.positions && typeof value.positions === "object" ? value.positions : {};
    Object.keys(MODES).forEach(mode => value.positions[mode] ||= {});
    state.profile.ideaMap = value;
    return value;
  };
  const persist = () => { writeLocalState(); scheduleCloudSave(); };
  const categoryKey = note => note.categoryId || (note.category ? `legacy:${note.category.toLocaleLowerCase("pt-BR")}` : "none");
  const category = note => categories.find(item => item.id === note.categoryId) || { id: categoryKey(note), name: note.category || "Sem categoria", color: note.color || "#25f47d" };
  const nodeType = note => ["idea", "project", "task", "goal", "note"].includes(note.type) ? note.type : note.favorite ? "project" : "idea";
  const importance = note => Math.max(1, Math.min(5, Number(note.importance) || ({ high: 4, medium: 3, low: 2 }[note.priority]) || 3));
  const endpoints = link => ({ source: String(link.sourceId || link.source || ""), target: String(link.targetId || link.target || "") });
  const world = point => ({ x: (point.x - canvas.clientWidth / 2) / camera.zoom + camera.x, y: (point.y - canvas.clientHeight / 2) / camera.zoom + camera.y });
  const screen = point => ({ x: (point.x - camera.x) * camera.zoom + canvas.clientWidth / 2, y: (point.y - camera.y) * camera.zoom + canvas.clientHeight / 2 });
  const pointOf = event => { const rect = canvas.getBoundingClientRect(); return { x: event.clientX - rect.left, y: event.clientY - rect.top }; };
  const nodeRadius = node => 10 + node.importance * 2.2 + Math.min(14, node.degree * 2.4);

  function rebuild(reheat = true) {
    const prior = new Map(nodes.map(node => [node.id, node]));
    const priorLinks = new Map(links.map(link => [link.id || `${link.source}:${link.target}`, link]));
    const store = config().positions[config().theme];
    nodes = notes().map((note, index) => {
      const old = prior.get(note.id), saved = store[note.id], seed = index * 2.399;
      return { id: note.id, note, type: nodeType(note), importance: importance(note), category: categoryKey(note), degree: 0,
        x: old?.x ?? saved?.x ?? Math.cos(seed) * (40 + Math.sqrt(index) * 25), y: old?.y ?? saved?.y ?? Math.sin(seed) * (40 + Math.sqrt(index) * 25),
        vx: old?.vx || 0, vy: old?.vy || 0, locked: saved?.locked === true, born: old?.born ?? performance.now() };
    });
    const ids = new Set(nodes.map(node => node.id));
    links = config().connections.map(link => { const edge = endpoints(link), old = priorLinks.get(link.id || `${edge.source}:${edge.target}`); return { ...link, ...edge, type: link.type || "related", born: old?.born ?? performance.now() }; }).filter(link => link.source !== link.target && ids.has(link.source) && ids.has(link.target));
    const byId = new Map(nodes.map(node => [node.id, node]));
    links.forEach(link => { byId.get(link.source).degree++; byId.get(link.target).degree++; });
    if (!selectionInitialized && nodes.length) { selectedId = nodes.slice().sort((a,b) => b.degree - a.degree || b.importance - a.importance)[0].id; selectionInitialized = true; }
    if (reheat) start(.9);
    updateStats();
  }

  function modeTarget(node) {
    const mode = config().theme;
    if (mode === "blackhole") { const angle = hash(node.id) * Math.PI * 2, radius = 55 + (5 - node.importance) * 82; return { x: Math.cos(angle) * radius, y: Math.sin(angle) * radius * .72, strength: .018 }; }
    if (mode === "earth") { const focus = selectedId || nodes.slice().sort((a, b) => b.degree - a.degree)[0]?.id, depth = graphDepth(focus, node.id), angle = hash(node.id) * Math.PI * 2, radius = depth < 0 ? 360 : depth * 115; return { x: Math.cos(angle) * radius, y: Math.sin(angle) * radius * .76, strength: .022 }; }
    if (mode === "brain") { const groups = [...new Set(nodes.map(item => item.category))], index = Math.max(0, groups.indexOf(node.category)), columns = Math.max(2, Math.ceil(Math.sqrt(groups.length))), col = index % columns, row = Math.floor(index / columns); return { x: (col - (columns - 1) / 2) * 260, y: (row - Math.floor(groups.length / columns) / 2) * 220, strength: .014 }; }
    if (node.id === selectedId) return { x: 0, y: 0, strength: .035 };
    const groups = [...new Set(nodes.map(item => item.category))], groupIndex = Math.max(0, groups.indexOf(node.category));
    const members = nodes.filter(item => item.category === node.category), memberIndex = members.findIndex(item => item.id === node.id);
    const groupAngle = groupIndex / Math.max(1, groups.length) * Math.PI * 2 - Math.PI / 2, orbit = groups.length < 2 ? 150 : 245 + (groupIndex % 2) * 32;
    const localAngle = memberIndex / Math.max(1, members.length) * Math.PI * 2 + groupAngle;
    return { x: Math.cos(groupAngle) * orbit + Math.cos(localAngle) * 68, y: Math.sin(groupAngle) * orbit * .72 + Math.sin(localAngle) * 52, strength: .014 };
  }
  function hash(text) { let value = 0; for (const char of text) value = (value * 31 + char.charCodeAt(0)) >>> 0; return (value % 10000) / 10000; }
  function graphDepth(source, target) { if (!source) return -1; if (source === target) return 0; const adjacent = new Map(nodes.map(node => [node.id, []])); links.forEach(link => { adjacent.get(link.source)?.push(link.target); adjacent.get(link.target)?.push(link.source); }); const queue = [[source, 0]], seen = new Set([source]); while (queue.length) { const [id, depth] = queue.shift(); for (const next of adjacent.get(id) || []) { if (next === target) return depth + 1; if (!seen.has(next) && depth < 5) { seen.add(next); queue.push([next, depth + 1]); } } } return -1; }

  function tick() {
    if (!nodes.length) return;
    const byId = new Map(nodes.map(node => [node.id, node]));
    const stride = nodes.length > 300 ? Math.ceil(nodes.length / 220) : 1;
    for (let i = 0; i < nodes.length; i++) for (let j = i + 1; j < nodes.length; j += stride) {
      const a = nodes[i], b = nodes[j], dx = b.x - a.x || .01, dy = b.y - a.y || .01, d2 = Math.max(64, dx * dx + dy * dy), d = Math.sqrt(d2);
      const repel = Math.min(3.8, 1450 / d2) * alpha, fx = dx / d * repel, fy = dy / d * repel;
      if (!a.locked) { a.vx -= fx; a.vy -= fy; } if (!b.locked) { b.vx += fx; b.vy += fy; }
      const minimum = nodeRadius(a) + nodeRadius(b) + 18;
      if (d < minimum) { const push = (minimum - d) * .035 * alpha; if (!a.locked) { a.vx -= dx / d * push; a.vy -= dy / d * push; } if (!b.locked) { b.vx += dx / d * push; b.vy += dy / d * push; } }
    }
    links.forEach(link => { const a = byId.get(link.source), b = byId.get(link.target); if (!a || !b) return; const dx = b.x - a.x, dy = b.y - a.y, d = Math.max(1, Math.hypot(dx, dy)), target = link.type === "part-of" ? 145 : 185, force = (d - target) * .0024 * alpha; if (!a.locked) { a.vx += dx / d * force; a.vy += dy / d * force; } if (!b.locked) { b.vx -= dx / d * force; b.vy -= dy / d * force; } });
    nodes.forEach(node => { const target = modeTarget(node); if (!node.locked) { node.vx += (target.x - node.x) * target.strength * alpha; node.vy += (target.y - node.y) * target.strength * alpha; node.vx *= .83; node.vy *= .83; node.x += node.vx; node.y += node.vy; } });
    alpha *= .975;
  }
  function start(value = .7) { alpha = Math.max(alpha, value); if (!running) { running = true; last = 0; raf = requestAnimationFrame(frame); } }
  function frame(time) { if (!canvas?.isConnected) { running = false; return; } if (!last || time - last > 13) { tick(); last = time; } draw(); if (alpha > .008 || gesture) raf = requestAnimationFrame(frame); else { running = false; savePositions(); } }
  function savePositions() { const store = config().positions[config().theme]; nodes.forEach(node => store[node.id] = { x: Math.round(node.x * 10) / 10, y: Math.round(node.y * 10) / 10, locked: node.locked }); persist(); }

  function filtered() { const type = typeFilter?.value || "all", cat = categoryFilter?.value || "all"; return nodes.filter(node => (type === "all" || node.type === type) && (cat === "all" || node.category === cat)); }
  function matchesSearch(node) { const query = String(search?.value || "").trim().toLocaleLowerCase("pt-BR"); return !query || `${node.note.title || ""} ${node.note.content || ""} ${(node.note.tags || []).join(" ")}`.toLocaleLowerCase("pt-BR").includes(query); }
  function relatedSet(id) { const set = new Set(id ? [id] : []); links.forEach(link => { if (link.source === id) set.add(link.target); if (link.target === id) set.add(link.source); }); return set; }
  function resize() { const ratio = devicePixelRatio || 1, width = canvas.clientWidth, height = canvas.clientHeight; if (canvas.width !== Math.round(width * ratio) || canvas.height !== Math.round(height * ratio)) { canvas.width = Math.round(width * ratio); canvas.height = Math.round(height * ratio); } ctx.setTransform(ratio, 0, 0, ratio, 0, 0); return { width, height, ratio }; }
  function draw() {
    if (!ctx) return; const { width, height } = resize(), light = document.body.classList.contains("light"), shown = new Set(filtered().map(node => node.id)), focus = selectedId || hoverId, related = relatedSet(focus), query = String(search?.value || "").trim();
    ctx.clearRect(0, 0, width, height); ctx.fillStyle = light ? "#f7faf8" : "#050807"; ctx.fillRect(0, 0, width, height); drawGrid(width, height, light);
    ctx.save(); ctx.translate(width / 2 - camera.x * camera.zoom, height / 2 - camera.y * camera.zoom); ctx.scale(camera.zoom, camera.zoom);
    drawModeBackdrop(light);
    links.forEach(link => { if (!shown.has(link.source) || !shown.has(link.target)) return; const a = nodes.find(node => node.id === link.source), b = nodes.find(node => node.id === link.target), active = !focus || link.source === focus || link.target === focus, progress = Math.min(1, (performance.now() - link.born) / 360), edgeColor = category(a.note).color || "#25f47d"; ctx.globalAlpha = focus && !active ? .09 : 1; ctx.strokeStyle = active && focus ? edgeColor : light ? "rgba(14,120,66,.28)" : `${edgeColor}55`; ctx.setLineDash(link.type === "related" ? [5 / camera.zoom, 5 / camera.zoom] : []); ctx.lineWidth = (active && focus ? 1.6 : 1) / camera.zoom; ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(a.x + (b.x - a.x) * progress, a.y + (b.y - a.y) * progress); ctx.stroke(); ctx.setLineDash([]); });
    const labels = [];
    nodes.forEach(node => { if (!shown.has(node.id)) return; const active = node.id === focus, near = related.has(node.id), searchDim = query && !matchesSearch(node), dim = (focus && !near) || searchDim, growth = Math.min(1, (performance.now() - node.born) / 280); ctx.globalAlpha = searchDim ? .1 : dim ? .46 : node.note.status === "paused" ? .58 : 1; const radius = nodeRadius(node) * (active ? 1.55 : node.degree >= 3 ? 1.12 : 1) * growth, color = category(node.note).color || "#25f47d"; ctx.shadowColor = color; ctx.shadowBlur = active ? 34 : 13; ctx.fillStyle = light ? "#f8fcf9" : "#07100b"; ctx.beginPath(); ctx.arc(node.x, node.y, radius, 0, Math.PI * 2); ctx.fill(); ctx.shadowBlur = 0; ctx.strokeStyle = node.note.status === "completed" ? "#718078" : color; ctx.lineWidth = (active ? 2.2 : 1.25) / camera.zoom; ctx.stroke(); if (active) { ctx.globalAlpha *= .55; ctx.beginPath(); ctx.arc(node.x, node.y, radius + 7 / camera.zoom, 0, Math.PI * 2); ctx.stroke(); }
      ctx.globalAlpha = searchDim ? .1 : dim ? .46 : 1; ctx.fillStyle = color; ctx.font = `${Math.max(9,Math.min(16,radius*.46)) / camera.zoom}px Inter, sans-serif`; ctx.textAlign = "center"; ctx.textBaseline = "middle"; ctx.fillText(String(node.note.emoji || "✦").slice(0,2),node.x,node.y); const showLabel = active || node.id === hoverId || (!searchDim && (camera.zoom > .62 || node.degree >= 1 || node.importance >= 4)); if (showLabel) labels.push({ node, radius, dim, color });
    });
    drawLabels(labels, light); ctx.restore(); ctx.globalAlpha = 1; drawMiniMap(width, height, light); drawEmpty(width, height); updateStats();
  }
  function drawGrid(width, height, light) { ctx.strokeStyle = light ? "rgba(20,70,45,.045)" : "rgba(255,255,255,.025)"; ctx.lineWidth = 1; const gap = 32; for (let x = 0; x < width; x += gap) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, height); ctx.stroke(); } for (let y = 0; y < height; y += gap) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(width, y); ctx.stroke(); } }
  function drawModeBackdrop(light) { const mode = config().theme; if (mode === "blackhole") { const gradient = ctx.createRadialGradient(0, 0, 3, 0, 0, 42); gradient.addColorStop(0, "#000"); gradient.addColorStop(.62, "#020303"); gradient.addColorStop(.78, "rgba(37,244,125,.2)"); gradient.addColorStop(1, "transparent"); ctx.fillStyle = gradient; ctx.beginPath(); ctx.arc(0, 0, 44, 0, Math.PI * 2); ctx.fill(); } if (mode === "earth") { ctx.strokeStyle = light ? "rgba(14,120,66,.09)" : "rgba(37,244,125,.07)"; ctx.lineWidth = 1 / camera.zoom; [115,230,345].forEach(radius => { ctx.beginPath(); ctx.arc(0, 0, radius, 0, Math.PI * 2); ctx.stroke(); }); } }
  function drawLabels(items, light) { const occupied = []; items.sort((a, b) => Number(b.node.id === selectedId) - Number(a.node.id === selectedId) || b.node.degree - a.node.degree).forEach(item => { const text = String(item.node.note.title || "Ideia").slice(0, 34), font = (item.node.id === selectedId ? 11 : 9) / Math.max(.78, camera.zoom), width = ctx.measureText(text).width + 8, box = { x: item.node.x - width / 2, y: item.node.y + item.radius + 7 / camera.zoom, w: width, h: 15 / camera.zoom }; if (occupied.some(other => box.x < other.x + other.w && box.x + box.w > other.x && box.y < other.y + other.h && box.y + box.h > other.y)) return; occupied.push(box); ctx.globalAlpha = item.dim ? .14 : 1; ctx.font = `${item.node.id === selectedId ? 700 : 600} ${font}px Inter, sans-serif`; ctx.textAlign = "center"; ctx.textBaseline = "top"; ctx.fillStyle = light ? "#33493d" : "#c4cec8"; ctx.fillText(text, item.node.x, box.y); }); }
  function drawMiniMap(width, height, light) { if (!nodes.length || width < 520) return; const box = { x: width - 142, y: height - 96, w: 126, h: 76 }, extent = Math.max(240, ...nodes.flatMap(node => [Math.abs(node.x), Math.abs(node.y)])), scale = Math.min(box.w, box.h) / (extent * 2.25); ctx.fillStyle = light ? "rgba(255,255,255,.9)" : "rgba(7,12,9,.82)"; ctx.strokeStyle = light ? "rgba(20,70,45,.16)" : "rgba(255,255,255,.12)"; ctx.fillRect(box.x, box.y, box.w, box.h); ctx.strokeRect(box.x, box.y, box.w, box.h); nodes.forEach(node => { ctx.fillStyle = "#25f47d"; ctx.globalAlpha = .65; ctx.beginPath(); ctx.arc(box.x + box.w / 2 + node.x * scale, box.y + box.h / 2 + node.y * scale, 1.2, 0, Math.PI * 2); ctx.fill(); }); const viewW = width / camera.zoom * scale, viewH = height / camera.zoom * scale; ctx.globalAlpha = 1; ctx.strokeStyle = "rgba(37,244,125,.65)"; ctx.strokeRect(box.x + box.w / 2 + (camera.x - width / camera.zoom / 2) * scale, box.y + box.h / 2 + (camera.y - height / camera.zoom / 2) * scale, viewW, viewH); }
  function drawEmpty(width, height) { const empty = root?.querySelector(".idea-empty-state"); if (empty) empty.hidden = nodes.length > 0; }

  function hit(point) { const target = world(point); return [...filtered()].reverse().find(node => Math.hypot(target.x - node.x, target.y - node.y) <= nodeRadius(node) + 9 / camera.zoom); }
  function bindCanvas() {
    canvas.oncontextmenu = event => event.preventDefault();
    canvas.onpointerdown = event => { pointers.set(event.pointerId, pointOf(event)); canvas.setPointerCapture(event.pointerId); const point = pointOf(event), node = hit(point); clearTimeout(longPress); if (node) { selectedId = node.id; renderDetail(); gesture = { type: "node", node, moved: false }; longPress = setTimeout(() => { if (gesture?.type === "node" && !gesture.moved) openNodeMenu(node); }, 650); } else gesture = { type: "pan", start: point, camera: { ...camera }, moved: false }; draw(); };
    canvas.onpointermove = event => { const point = pointOf(event); pointers.set(event.pointerId, point); if (pointers.size === 2) { const values = [...pointers.values()], distance = Math.hypot(values[0].x - values[1].x, values[0].y - values[1].y); if (!gesture || gesture.type !== "pinch") gesture = { type: "pinch", distance, zoom: camera.zoom }; else camera.zoom = Math.max(.25, Math.min(4, gesture.zoom * distance / gesture.distance)); draw(); return; } const node = hit(point); hoverId = node?.id || ""; if (gesture?.type === "node") { const value = world(point); gesture.moved ||= Math.hypot(value.x - gesture.node.x, value.y - gesture.node.y) > 4; if (gesture.moved && !gesture.node.locked) { gesture.node.x = value.x; gesture.node.y = value.y; gesture.node.vx = gesture.node.vy = 0; } } else if (gesture?.type === "pan") { gesture.moved ||= Math.hypot(point.x - gesture.start.x, point.y - gesture.start.y) > 3; camera.x = gesture.camera.x - (point.x - gesture.start.x) / camera.zoom; camera.y = gesture.camera.y - (point.y - gesture.start.y) / camera.zoom; } draw(); };
    canvas.onpointerup = event => { pointers.delete(event.pointerId); clearTimeout(longPress); if (gesture?.type === "node" && gesture.moved) savePositions(); gesture = null; draw(); };
    canvas.onpointercancel = canvas.onpointerup; canvas.onpointerleave = () => { if (!gesture) { hoverId = ""; draw(); } };
    canvas.onwheel = event => { event.preventDefault(); const before = world(pointOf(event)), factor = event.deltaY > 0 ? .9 : 1.1; camera.zoom = Math.max(.25, Math.min(4, camera.zoom * factor)); const after = world(pointOf(event)); camera.x += before.x - after.x; camera.y += before.y - after.y; draw(); };
    canvas.ondblclick = event => { const point = pointOf(event), node = hit(point); if (node) openForm("notes", node.id); else openCreate(world(point), selectedId); };
  }

  function renderDetail() {
    const node = nodes.find(item => item.id === selectedId); root?.querySelector(".idea-map-layout")?.classList.toggle("has-selection", !!node); if (!detail) return;
    if (!node) { detail.innerHTML = `<div class="idea-detail-empty"><i>●</i><b>Selecione uma ideia</b><small>Explore relações, detalhes e ações sem sair do mapa.</small></div>`; return; }
    const note = node.note, connected = links.filter(link => link.source === node.id || link.target === node.id), tags = Array.isArray(note.tags) ? note.tags : String(note.tags || "").split(",").map(tag => tag.trim()).filter(Boolean);
    detail.innerHTML = `<header><div><span>${node.type.toUpperCase()}</span><h3></h3></div><button type="button" class="idea-detail-close" aria-label="Fechar">×</button></header><p></p><section><small>CONEXÕES · ${connected.length}</small><div class="idea-connections-list"></div></section><section><small>TAGS</small><div class="idea-tags"></div></section><div class="idea-detail-actions"><button type="button" data-connect>＋ Conectar</button><button type="button" data-related>＋ Ideia relacionada</button><button type="button" data-edit>Editar</button><button type="button" class="danger" data-delete>Excluir</button></div>`;
    detail.querySelector("h3").textContent = note.title || "Ideia sem título"; detail.querySelector("p").textContent = note.content || note.description || "Sem descrição.";
    const list = detail.querySelector(".idea-connections-list"); connected.forEach(link => { const other = nodes.find(item => item.id === (link.source === node.id ? link.target : link.source)), button = document.createElement("button"); button.type = "button"; button.innerHTML = `<i>→</i><span><b></b><small>${LINK_TYPES[link.type] || LINK_TYPES.related}</small></span>`; button.querySelector("b").textContent = other?.note.title || "Ideia removida"; button.onclick = () => { if (other) { selectedId = other.id; renderDetail(); draw(); } }; list.appendChild(button); });
    detail.querySelector(".idea-tags").innerHTML = tags.length ? tags.map(tag => `<span>#${safe(tag.replace(/^#/, ""))}</span>`).join("") : "<em>Sem tags</em>";
    detail.querySelector(".idea-detail-close").onclick = () => { selectedId = ""; renderDetail(); draw(); };
    detail.querySelector("[data-edit]").onclick = () => openForm("notes", note.id); detail.querySelector("[data-related]").onclick = () => openCreate({ x: node.x + 60, y: node.y + 30 }, node.id); detail.querySelector("[data-connect]").onclick = () => openConnect(node.id);
    detail.querySelector("[data-delete]").onclick = () => { if (!confirm("Excluir esta ideia e suas conexões?")) return; state.notes = notes().filter(item => item.id !== node.id); config().connections = config().connections.filter(link => { const edge = endpoints(link); return edge.source !== node.id && edge.target !== node.id; }); Object.values(config().positions).forEach(store => delete store[node.id]); selectedId = ""; persist(); rebuild(); renderNotesPage?.(); renderDetail(); };
  }
  function openCreate(point = { x: 0, y: 0 }, parentId = "") { openGraphModal("Nova ideia", `<label>Título<input name="title" required maxlength="100" autofocus></label><label>Descrição<textarea name="description" rows="3"></textarea></label><label>Tipo<select name="type"><option value="idea">Ideia</option><option value="project">Projeto</option><option value="task">Tarefa</option><option value="goal">Meta</option><option value="note">Nota</option></select></label><label>Tags<input name="tags" placeholder="startup, site, produtividade"></label><button class="primary" type="submit">Criar ideia</button>`, data => { const note = { id: `note-${id()}`, title: data.get("title").trim(), content: data.get("description").trim(), type: data.get("type"), tags: data.get("tags").split(",").map(tag => tag.trim()).filter(Boolean), importance: 3, priority: "medium", status: "active", size: "medium", glow: "medium", color: "#25f47d", emoji: "●", createdAt: new Date().toISOString(), parentId: parentId || undefined }; state.notes.push(note); config().positions[config().theme][note.id] = { x: point.x, y: point.y, locked: false }; if (parentId) config().connections.push({ id: `connection-${id()}`, sourceId: parentId, targetId: note.id, type: "created-from" }); selectedId = note.id; persist(); rebuild(); renderNotesPage?.(); renderDetail(); }); }
  function openConnect(sourceId) { const options = nodes.filter(node => node.id !== sourceId && !links.some(link => (link.source === sourceId && link.target === node.id) || (link.target === sourceId && link.source === node.id))); openGraphModal("Criar conexão", `<label>Relacionar com<select name="target" required><option value="">Selecione</option>${options.map(node => `<option value="${safe(node.id)}">${safe(node.note.title || "Ideia")}</option>`).join("")}</select></label><label>Tipo de relação<select name="type">${Object.entries(LINK_TYPES).map(([value, label]) => `<option value="${value}">${label}</option>`).join("")}</select></label><button class="primary" type="submit">Conectar ideias</button>`, data => { const target = data.get("target"); if (!target) return; config().connections.push({ id: `connection-${id()}`, sourceId, targetId: target, type: data.get("type") }); persist(); rebuild(); renderDetail(); }); }
  function openGraphModal(title, fields, submit) { root.querySelector(".idea-graph-modal")?.remove(); const layer = document.createElement("div"); layer.className = "idea-graph-modal"; layer.innerHTML = `<form><header><h3>${title}</h3><button type="button" aria-label="Fechar">×</button></header>${fields}</form>`; root.appendChild(layer); const form = layer.querySelector("form"); layer.onclick = event => { if (event.target === layer) layer.remove(); }; form.querySelector("header button").onclick = () => layer.remove(); form.onsubmit = event => { event.preventDefault(); submit(new FormData(form)); layer.remove(); }; setTimeout(() => form.querySelector("input,select,textarea")?.focus(), 0); }
  function openNodeMenu(node) { selectedId = node.id; renderDetail(); root.querySelector(".idea-map-layout")?.classList.add("mobile-detail-open"); draw(); }

  function populateFilters() { if (!categoryFilter) return; const legacy = [...new Set(notes().filter(note => !note.categoryId && note.category).map(note => note.category))], values=[{id:"all",name:"Todas",color:"#25f47d"},{id:"none",name:"Sem categoria",color:"#77827b"},...categories,...legacy.map(name=>({id:`legacy:${name.toLocaleLowerCase("pt-BR")}`,name,color:"#8aa6ff"}))]; categoryFilter.replaceChildren(new Option("Todas as categorias", "all"), new Option("Sem categoria", "none"), ...categories.map(item => new Option(item.name, item.id)), ...legacy.map(name => new Option(name, `legacy:${name.toLocaleLowerCase("pt-BR")}`))); categoryFilter.value = [...categoryFilter.options].some(option => option.value === config().selectedCategory) ? config().selectedCategory : "all"; const chips=root?.querySelector('.idea-category-chips');if(chips){chips.innerHTML=values.slice(0,8).map(item=>`<button data-idea-category="${safe(item.id)}" class="${item.id===categoryFilter.value?'active':''}" style="--chip:${safe(item.color||'#25f47d')}"><i></i><span>${safe(item.name)}</span><em>${item.id==='all'?notes().length:notes().filter(note=>categoryKey(note)===item.id).length}</em></button>`).join('');chips.querySelectorAll('button').forEach(button=>button.onclick=()=>{categoryFilter.value=button.dataset.ideaCategory;categoryFilter.onchange()})} }
  async function loadCategories() { try { categories = await window.LuarCategories?.list("knowledge", true) || []; } catch { categories = []; } populateFilters(); rebuild(); }
  function updateStats() { const stats = root?.querySelector(".idea-map-stats"); if (!stats) return; stats.textContent = `${nodes.length} ideias · ${links.length} conexões · ${new Set(nodes.map(node => node.category)).size} grupos`; }
  function center(fit = false) { if (!nodes.length) return; const minX = Math.min(...nodes.map(node => node.x)), maxX = Math.max(...nodes.map(node => node.x)), minY = Math.min(...nodes.map(node => node.y)), maxY = Math.max(...nodes.map(node => node.y)); camera.x = (minX + maxX) / 2; camera.y = (minY + maxY) / 2; if (fit) camera.zoom = Math.max(.3, Math.min(1.35, Math.min((canvas.clientWidth - 100) / Math.max(180, maxX - minX), (canvas.clientHeight - 100) / Math.max(160, maxY - minY)))); draw(); }
  function focusSearch() { const result = filtered().find(matchesSearch); if (!String(search.value || "").trim() || !result) { draw(); return; } camera.x = result.x; camera.y = result.y; camera.zoom = Math.max(1.25, camera.zoom); selectedId = result.id; renderDetail(); draw(); }

  function build() {
    root = document.getElementById("ideaMapApp"); if (!root || root.dataset.graphEngine) return; root.dataset.graphEngine = "force-v2";
    root.innerHTML = `<article class="idea-map-shell"><div class="idea-map-toolbar"><div class="idea-mode-tabs">${Object.entries(MODES).map(([value, label]) => `<button type="button" data-mode="${value}">${label}</button>`).join("")}</div><label class="idea-map-search"><i>⌕</i><input id="ideaMapSearch" type="search" placeholder="Buscar ideias, conexões, tags..."></label><button type="button" class="idea-filter-button" aria-expanded="true">☷ Filtros <b>0</b></button><div class="idea-map-actions"><button type="button" data-zoom="out" aria-label="Diminuir zoom">−</button><button type="button" data-zoom="in" aria-label="Aumentar zoom">＋</button><button type="button" data-center>Centralizar</button><button type="button" data-arrange>Reorganizar</button><button type="button" class="idea-new-button">＋ Nova ideia</button></div></div><div class="idea-map-layout"><aside class="idea-filter-drawer"><header><span>EXPLORAR</span><b>Organize sua mente</b></header><label>Mostrar<select id="ideaTypeFilter"><option value="all">Todas as ideias</option><option value="project">Projetos</option><option value="idea">Ideias</option><option value="task">Tarefas</option><option value="goal">Metas</option><option value="note">Notas</option></select></label><div class="idea-type-chips">${[["all","Todas"],["project","Projetos"],["goal","Metas"],["task","Tarefas"]].map(([id,name])=>`<button data-idea-type="${id}" class="${id==='all'?'active':''}">${name}</button>`).join('')}</div><label>Categoria<select id="ideaCategoryFilter"></select></label><div class="idea-category-chips"></div><section><small>VISUALIZAÇÃO</small><p>Ideias e conexões</p><p>Tags e grupos</p><p>Posições preservadas</p></section><div class="idea-map-stats"></div></aside><div class="idea-canvas-wrap"><canvas id="ideaMapCanvas" aria-label="Grafo interativo de conhecimento"></canvas><div class="idea-empty-state" hidden><i>●</i><h3>Sua mente começa aqui.</h3><p>Conecte uma primeira ideia e veja seus pensamentos ganharem forma.</p><button type="button">＋ Criar primeira ideia</button></div><div class="idea-map-help">Scroll para zoom · Arraste para explorar · Duplo clique para criar</div></div><aside class="idea-detail" id="ideaMapDetail"></aside></div></article>`;
    canvas = root.querySelector("canvas"); ctx = canvas.getContext("2d"); detail = root.querySelector("#ideaMapDetail"); search = root.querySelector("#ideaMapSearch"); typeFilter = root.querySelector("#ideaTypeFilter"); categoryFilter = root.querySelector("#ideaCategoryFilter");
    bindCanvas(); renderDetail(); root.querySelectorAll("[data-mode]").forEach(button => { button.classList.toggle("active", button.dataset.mode === config().theme); button.onclick = () => { config().theme = button.dataset.mode; root.querySelectorAll("[data-mode]").forEach(item => item.classList.toggle("active", item === button)); rebuild(); persist(); }; });
    search.oninput = focusSearch; typeFilter.onchange = () => { root.querySelectorAll('[data-idea-type]').forEach(button=>button.classList.toggle('active',button.dataset.ideaType===typeFilter.value)); draw(); }; root.querySelectorAll('[data-idea-type]').forEach(button=>button.onclick=()=>{typeFilter.value=button.dataset.ideaType;typeFilter.onchange()}); categoryFilter.onchange = () => { config().selectedCategory = categoryFilter.value; root.querySelectorAll('[data-idea-category]').forEach(button=>button.classList.toggle('active',button.dataset.ideaCategory===categoryFilter.value)); draw(); persist(); }; const filterButton = root.querySelector(".idea-filter-button"), drawer = root.querySelector(".idea-filter-drawer"); filterButton.onclick = () => { drawer.classList.toggle("collapsed"); filterButton.setAttribute("aria-expanded", String(!drawer.classList.contains("collapsed"))); }; root.querySelector(".idea-new-button").onclick = () => openCreate(world({x:canvas.clientWidth/2,y:canvas.clientHeight/2}));
    root.querySelector('[data-zoom="out"]').onclick = () => { camera.zoom = Math.max(.25, camera.zoom * .82); draw(); }; root.querySelector('[data-zoom="in"]').onclick = () => { camera.zoom = Math.min(4, camera.zoom * 1.22); draw(); }; root.querySelector("[data-center]").onclick = () => center(true); root.querySelector("[data-arrange]").onclick = () => { config().positions[config().theme] = {}; nodes.forEach(node => node.locked = false); rebuild(); };
    root.querySelector(".idea-empty-state button").onclick = () => openCreate(); mainResizeObserver?.disconnect(); mainResizeObserver = new ResizeObserver(draw); mainResizeObserver.observe(canvas); loadCategories(); rebuild();
  }

  function renderDashboardMiniMap() {
    const host = document.getElementById("dashboardIdeaMapSlot") || document.getElementById("dashboardWidgetZone"); if (!host) return; host.querySelector(".dashboard-idea-map-widget")?.remove(); const card = document.createElement("article"); card.className = "dashboard-idea-map-widget"; card.innerHTML = `<header><span><small>MAPA DE IDEIAS</small><b>${notes().length} ideias conectadas</b></span><button type="button">Abrir ↗</button></header><canvas></canvas>`; host.appendChild(card); card.querySelector("button").onclick = () => showPage("notes"); const mini = card.querySelector("canvas"), positions = config().positions.free; notes().forEach((note, index) => { if (!positions[note.id]) { const angle = index * 2.399; positions[note.id] = { x: Math.cos(angle) * (35 + Math.sqrt(index) * 24), y: Math.sin(angle) * (35 + Math.sqrt(index) * 24), locked: false }; } }); const paint = () => { const box = mini.getBoundingClientRect(), ratio = devicePixelRatio || 1; mini.width = box.width * ratio; mini.height = box.height * ratio; const context = mini.getContext("2d"); context.setTransform(ratio, 0, 0, ratio, 0, 0); context.clearRect(0, 0, box.width, box.height); context.fillStyle = document.body.classList.contains("light") ? "#f7faf8" : "#050807"; context.fillRect(0, 0, box.width, box.height); const points = notes().map(note => ({ note, point: positions[note.id] })).filter(item => item.point), extent = Math.max(180, ...points.flatMap(item => [Math.abs(item.point.x), Math.abs(item.point.y)])), scale = Math.min(box.width, box.height) / extent / 2.3; context.translate(box.width / 2, box.height / 2); context.strokeStyle = "rgba(37,244,125,.16)"; config().connections.forEach(link => { const edge = endpoints(link), a = positions[edge.source], b = positions[edge.target]; if (!a || !b) return; context.beginPath(); context.moveTo(a.x * scale, a.y * scale); context.lineTo(b.x * scale, b.y * scale); context.stroke(); }); context.fillStyle = "#25f47d"; points.forEach(({ point }) => { context.beginPath(); context.arc(point.x * scale, point.y * scale, 2.2, 0, Math.PI * 2); context.fill(); }); }; new ResizeObserver(paint).observe(mini); paint();
  }
  function renderDashboardOverview() {
    const host = document.getElementById("dashboardIdeaMapSlot") || document.getElementById("dashboardWidgetZone"); if (!host) return;
    let card = host.querySelector(".dashboard-idea-map-widget");
    if (!card) { card = document.createElement("article"); card.className = "dashboard-idea-map-widget"; card.innerHTML = `<header><span><small>MAPA DE IDEIAS</small><b></b></span><button type="button">Abrir ↗</button></header><canvas></canvas>`; host.replaceChildren(card); card.querySelector("button").onclick = () => showPage("notes"); }
    card.querySelector("header b").textContent = `${notes().length} ideias conectadas`;
    const mini = card.querySelector("canvas"), positions = config().positions.free;
    notes().forEach((note, index) => { if (!positions[note.id]) { const angle = index * 2.399; positions[note.id] = { x: Math.cos(angle) * (35 + Math.sqrt(index) * 24), y: Math.sin(angle) * (35 + Math.sqrt(index) * 24), locked: false }; } });
    const paint = () => { if (!mini.isConnected) return; const box = mini.getBoundingClientRect(), ratio = Math.min(2, devicePixelRatio || 1), width = Math.max(1, Math.round(box.width * ratio)), height = Math.max(1, Math.round(box.height * ratio)); if (mini.width !== width) mini.width = width; if (mini.height !== height) mini.height = height; const context = mini.getContext("2d"); context.setTransform(ratio, 0, 0, ratio, 0, 0); context.clearRect(0, 0, box.width, box.height); context.fillStyle = document.body.classList.contains("light") ? "#f7faf8" : "#050807"; context.fillRect(0, 0, box.width, box.height); const points = notes().map(note => ({ note, point: positions[note.id] })).filter(item => item.point), extent = Math.max(180, ...points.flatMap(item => [Math.abs(item.point.x), Math.abs(item.point.y)])), scale = Math.min(box.width, box.height) / extent / 2.3; context.translate(box.width / 2, box.height / 2); context.strokeStyle = "rgba(37,244,125,.16)"; config().connections.forEach(link => { const edge = endpoints(link), a = positions[edge.source], b = positions[edge.target]; if (!a || !b) return; context.beginPath(); context.moveTo(a.x * scale, a.y * scale); context.lineTo(b.x * scale, b.y * scale); context.stroke(); }); context.fillStyle = "#25f47d"; points.forEach(({ point }) => { context.beginPath(); context.arc(point.x * scale, point.y * scale, 2.4, 0, Math.PI * 2); context.fill(); }); };
    miniResizeObserver?.disconnect(); miniResizeObserver = new ResizeObserver(paint); miniResizeObserver.observe(mini); paint();
  }
  function render() { build(); if (!root) return; rebuild(false); populateFilters(); renderDetail(); draw(); }
  function renderFromApp() { if (document.getElementById("notes")?.classList.contains("active")) render(); }
  window.LuarIdeaMap = { render, renderFromApp, arrange: () => rebuild(), renderDashboard: renderDashboardOverview, refreshTheme: draw, debug: () => ({ nodes, links, alpha, camera }) };
  window.addEventListener("luar:categories-changed", event => { if (event.detail?.domain === "knowledge") loadCategories(); });
  document.addEventListener("click", event => { const button = event.target.closest('[data-action="delete"][data-entity="notes"]'); if (!button) return; const noteId = button.dataset.id; config().connections = config().connections.filter(link => { const edge = endpoints(link); return edge.source !== noteId && edge.target !== noteId; }); Object.values(config().positions).forEach(store => delete store[noteId]); }, true);
  document.addEventListener("DOMContentLoaded", renderFromApp, { once: true }); setTimeout(renderFromApp, 0);
})();
