begin;

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('admin')),
  granted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  user_email text not null,
  kind text not null check (kind in ('suggestion', 'problem', 'review')),
  message text not null check (char_length(message) between 10 and 1800),
  rating smallint check (rating between 1 and 5),
  publish_authorized boolean not null default false,
  status text not null default 'pending' check (status in ('pending', 'reviewing', 'approved', 'rejected', 'implemented')),
  admin_response text check (admin_response is null or char_length(admin_response) <= 1800),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  action text not null check (char_length(action) between 3 and 80),
  target_type text not null check (char_length(target_type) between 2 and 40),
  target_id text not null check (char_length(target_id) between 1 and 254),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now()
);

create index if not exists admin_feedback_status_created_idx on public.admin_feedback(status, created_at desc);
create index if not exists admin_feedback_user_idx on public.admin_feedback(user_id, created_at desc);
create index if not exists admin_audit_logs_created_idx on public.admin_audit_logs(created_at desc);

alter table public.user_roles enable row level security;
alter table public.admin_feedback enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.luar_accounts enable row level security;
alter table public.luar_payments enable row level security;
alter table public.luar_lifetime_admin_audit enable row level security;
alter table public.luar_referral_profiles enable row level security;
alter table public.luar_referrals enable row level security;

create or replace function public.is_luar_admin(p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select p_user_id is not null and exists (
    select 1 from public.user_roles role_row
    where role_row.user_id = p_user_id and role_row.role = 'admin'
  );
$$;

revoke all on function public.is_luar_admin(uuid) from public, anon;
grant execute on function public.is_luar_admin(uuid) to authenticated;

drop policy if exists user_roles_admin_select on public.user_roles;
create policy user_roles_admin_select on public.user_roles for select to authenticated
using (public.is_luar_admin());

drop policy if exists admin_feedback_owner_insert on public.admin_feedback;
create policy admin_feedback_owner_insert on public.admin_feedback for insert to authenticated
with check (user_id = auth.uid() and lower(user_email) = lower(coalesce(auth.jwt()->>'email', '')));
drop policy if exists admin_feedback_admin_select on public.admin_feedback;
create policy admin_feedback_admin_select on public.admin_feedback for select to authenticated
using (public.is_luar_admin());
drop policy if exists admin_feedback_admin_update on public.admin_feedback;
create policy admin_feedback_admin_update on public.admin_feedback for update to authenticated
using (public.is_luar_admin()) with check (public.is_luar_admin());

drop policy if exists admin_audit_admin_select on public.admin_audit_logs;
create policy admin_audit_admin_select on public.admin_audit_logs for select to authenticated
using (public.is_luar_admin());

grant select on public.user_roles to authenticated;
grant select, insert, update on public.admin_feedback to authenticated;
grant select on public.admin_audit_logs to authenticated;
grant usage, select on sequence public.admin_feedback_id_seq to authenticated;

insert into public.user_roles (user_id, role, granted_by)
select id, 'admin', id from auth.users
where lower(email) = 'msgdo.2007@gmail.com'
on conflict (user_id) do update set role = excluded.role, updated_at = now();

create or replace function public.require_luar_admin(p_require_aal2 boolean default true)
returns uuid
language plpgsql
stable
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_aal text := coalesce(auth.jwt()->>'aal', 'aal1');
begin
  if not public.is_luar_admin(v_user_id) then
    raise exception 'ADMIN_FORBIDDEN' using errcode = '42501';
  end if;
  if p_require_aal2 and v_aal <> 'aal2' then
    raise exception 'MFA_REQUIRED' using errcode = '42501';
  end if;
  return v_user_id;
end;
$$;

revoke all on function public.require_luar_admin(boolean) from public, anon;
grant execute on function public.require_luar_admin(boolean) to authenticated;

create or replace function public.admin_dashboard_metrics()
returns jsonb
language plpgsql
stable
security definer
set search_path = public, auth, pg_temp
as $$
declare v_actor uuid;
begin
  v_actor := public.require_luar_admin(true);
  return jsonb_build_object(
    'totalUsers', (select count(*) from auth.users),
    'dau', (select count(*) from public.luar_accounts where last_login_at >= (date_trunc('day', now() at time zone 'America/Sao_Paulo') at time zone 'America/Sao_Paulo')),
    'mau', (select count(*) from public.luar_accounts where last_login_at >= (date_trunc('month', now() at time zone 'America/Sao_Paulo') at time zone 'America/Sao_Paulo')),
    'lifetimeAccounts', (select count(*) from public.luar_accounts where plan = 'lifetime'),
    'mrrCents', 0,
    'pendingFeedback', (select count(*) from public.admin_feedback where status = 'pending')
  );
end;
$$;

create or replace function public.admin_list_users(
  p_search text default '', p_status text default 'all', p_page integer default 1, p_page_size integer default 20
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_actor uuid;
  v_search text := left(lower(btrim(coalesce(p_search, ''))), 120);
  v_status text := lower(coalesce(p_status, 'all'));
  v_page integer := greatest(1, least(coalesce(p_page, 1), 100000));
  v_size integer := greatest(5, least(coalesce(p_page_size, 20), 100));
  v_total bigint;
  v_items jsonb;
begin
  v_actor := public.require_luar_admin(true);
  if v_status not in ('all', 'active', 'banned', 'lifetime') then raise exception 'FILTER_INVALID'; end if;
  with rows as (
    select u.id, lower(u.email) email, coalesce(u.raw_user_meta_data->>'name', split_part(u.email, '@', 1)) name,
      u.created_at, u.last_sign_in_at, u.banned_until,
      coalesce(a.plan, 'free') plan, coalesce(a.lifetime_source, 'none') lifetime_source,
      coalesce(a.login_count, 0) login_count, a.last_login_at,
      case when coalesce(a.state->'profile'->>'xp','') ~ '^-?[0-9]+([.][0-9]+)?$' then (a.state->'profile'->>'xp')::numeric else 0 end xp
    from auth.users u left join public.luar_accounts a on a.email = lower(u.email)
    where (v_search = '' or lower(u.email) like '%' || v_search || '%' or lower(coalesce(u.raw_user_meta_data->>'name', '')) like '%' || v_search || '%')
      and (v_status = 'all' or (v_status = 'active' and (u.banned_until is null or u.banned_until <= now())) or (v_status = 'banned' and u.banned_until > now()) or (v_status = 'lifetime' and a.plan = 'lifetime'))
  ), counted as (select count(*) total from rows), paged as (
    select * from rows order by created_at desc offset (v_page - 1) * v_size limit v_size
  )
  select counted.total, coalesce((select jsonb_agg(to_jsonb(paged)) from paged), '[]'::jsonb)
  into v_total, v_items from counted;
  return jsonb_build_object('items', v_items, 'total', v_total, 'page', v_page, 'pageSize', v_size);
end;
$$;

create or replace function public.admin_rankings(p_kind text default 'xp', p_limit integer default 50)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, auth, pg_temp
as $$
declare v_actor uuid; v_kind text := lower(coalesce(p_kind, 'xp')); v_limit integer := greatest(5, least(coalesce(p_limit, 50), 100)); v_items jsonb;
begin
  v_actor := public.require_luar_admin(true);
  if v_kind not in ('xp', 'balance') then raise exception 'RANKING_INVALID'; end if;
  with values_by_account as (
    select a.email, coalesce(u.raw_user_meta_data->>'name', split_part(a.email, '@', 1)) name,
      case when coalesce(a.state->'profile'->>'xp','') ~ '^-?[0-9]+([.][0-9]+)?$' then (a.state->'profile'->>'xp')::numeric else 0 end xp,
      coalesce((select sum(case when item->>'type' = 'income' then 1 else -1 end * case when coalesce(item->>'amount','') ~ '^-?[0-9]+([.][0-9]+)?$' then (item->>'amount')::numeric else 0 end) from jsonb_array_elements(case when jsonb_typeof(a.state->'transactions')='array' then a.state->'transactions' else '[]'::jsonb end) item),0) balance
    from public.luar_accounts a left join auth.users u on lower(u.email)=a.email
  ), ranked as (
    select email, name, xp, balance, dense_rank() over(order by case when v_kind='xp' then xp else balance end desc) position
    from values_by_account order by case when v_kind='xp' then xp else balance end desc limit v_limit
  )
  select coalesce(jsonb_agg(to_jsonb(ranked)), '[]'::jsonb) into v_items from ranked;
  return v_items;
end;
$$;

create or replace function public.admin_set_lifetime(p_target_email text, p_action text)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_actor uuid; v_email text := lower(btrim(coalesce(p_target_email,''))); v_action text := lower(coalesce(p_action,''));
  v_account public.luar_accounts%rowtype; v_provider text := 'email'; v_result_plan text; v_result_source text;
begin
  v_actor := public.require_luar_admin(true);
  if v_action not in ('grant','revoke') or char_length(v_email) > 254 or v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then raise exception 'INPUT_INVALID'; end if;
  perform pg_advisory_xact_lock(hashtextextended(v_email, 0));
  select coalesce(i.provider,'email') into v_provider from auth.users u left join auth.identities i on i.user_id=u.id where lower(u.email)=v_email order by i.last_sign_in_at desc nulls last limit 1;
  v_provider := case when v_provider in ('google','discord','email') then v_provider else 'email' end;
  select * into v_account from public.luar_accounts where email=v_email for update;
  if v_action='revoke' and found and v_account.plan='lifetime' and coalesce(v_account.lifetime_source,'none') <> 'admin' then raise exception 'PERMANENT_LIFETIME'; end if;
  if v_action='grant' then
    insert into public.luar_accounts(email,plan,lifetime_paid_at,lifetime_source,lifetime_provider,lifetime_granted_by,lifetime_granted_at,updated_at)
    values(v_email,'lifetime',now(),'admin',v_provider,v_actor,now(),now())
    on conflict(email) do update set
      plan=case when public.luar_accounts.plan='lifetime' then public.luar_accounts.plan else 'lifetime' end,
      lifetime_source=case when public.luar_accounts.plan='lifetime' and public.luar_accounts.lifetime_source<>'admin' then public.luar_accounts.lifetime_source else 'admin' end,
      lifetime_provider=coalesce(public.luar_accounts.lifetime_provider,excluded.lifetime_provider),
      lifetime_paid_at=coalesce(public.luar_accounts.lifetime_paid_at,excluded.lifetime_paid_at),
      lifetime_granted_by=case when public.luar_accounts.plan='lifetime' and public.luar_accounts.lifetime_source<>'admin' then public.luar_accounts.lifetime_granted_by else v_actor end,
      lifetime_granted_at=coalesce(public.luar_accounts.lifetime_granted_at,now()), lifetime_revoked_at=null, updated_at=now();
  else
    if found and v_account.plan='lifetime' then
      perform set_config('luar.admin_revoke','1',true);
      update public.luar_accounts set plan='free',lifetime_paid_at=null,lifetime_transaction_id=null,lifetime_source='none',lifetime_provider=null,lifetime_granted_by=null,lifetime_granted_at=null,lifetime_revoked_at=now(),updated_at=now() where email=v_email;
    end if;
  end if;
  select plan,lifetime_source into v_result_plan,v_result_source from public.luar_accounts where email=v_email;
  insert into public.admin_audit_logs(actor_user_id,action,target_type,target_id,metadata) values(v_actor,'lifetime_'||v_action,'user',v_email,jsonb_build_object('plan',coalesce(v_result_plan,'free'),'source',coalesce(v_result_source,'none')));
  return jsonb_build_object('email',v_email,'plan',coalesce(v_result_plan,'free'),'source',coalesce(v_result_source,'none'));
end;
$$;

create or replace function public.admin_update_feedback(p_id bigint, p_status text, p_response text default null)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare v_actor uuid; v_status text := lower(coalesce(p_status,'')); v_response text := nullif(btrim(coalesce(p_response,'')),''); v_row public.admin_feedback%rowtype;
begin
  v_actor := public.require_luar_admin(true);
  if v_status not in ('pending','reviewing','approved','rejected','implemented') or char_length(coalesce(v_response,'')) > 1800 then raise exception 'INPUT_INVALID'; end if;
  update public.admin_feedback set status=v_status,admin_response=v_response,reviewed_by=v_actor,reviewed_at=now(),updated_at=now() where id=p_id returning * into v_row;
  if not found then raise exception 'NOT_FOUND'; end if;
  insert into public.admin_audit_logs(actor_user_id,action,target_type,target_id,metadata) values(v_actor,'feedback_update','feedback',p_id::text,jsonb_build_object('status',v_status));
  return to_jsonb(v_row);
end;
$$;

revoke all on function public.admin_dashboard_metrics() from public, anon;
revoke all on function public.admin_list_users(text,text,integer,integer) from public, anon;
revoke all on function public.admin_rankings(text,integer) from public, anon;
revoke all on function public.admin_set_lifetime(text,text) from public, anon;
revoke all on function public.admin_update_feedback(bigint,text,text) from public, anon;
grant execute on function public.admin_dashboard_metrics() to authenticated;
grant execute on function public.admin_list_users(text,text,integer,integer) to authenticated;
grant execute on function public.admin_rankings(text,integer) to authenticated;
grant execute on function public.admin_set_lifetime(text,text) to authenticated;
grant execute on function public.admin_update_feedback(bigint,text,text) to authenticated;

commit;
