-- Phase 7: explicit referral states and immutable server-side audit trail.
-- Additive migration: existing verified referrals remain verified.

alter table public.luar_referrals
  drop constraint if exists luar_referrals_status_check;

alter table public.luar_referrals
  add constraint luar_referrals_status_check
  check (status in ('pending', 'verified', 'approved', 'rejected', 'cancelled'));

alter table public.luar_referrals
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists attributed_at timestamptz not null default now(),
  add column if not exists approved_at timestamptz,
  add column if not exists rejected_at timestamptz,
  add column if not exists cancelled_at timestamptz,
  add column if not exists status_reason text;

create index if not exists luar_referrals_referrer_status_idx
  on public.luar_referrals(referrer_user_id, status, created_at desc);

create index if not exists luar_referrals_referred_status_idx
  on public.luar_referrals(referred_user_id, status);

create table if not exists public.luar_referral_audit (
  id bigint generated by default as identity primary key,
  referral_id bigint not null references public.luar_referrals(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_type text not null check (actor_type in ('system', 'user', 'admin', 'payment')),
  previous_status text check (previous_status is null or previous_status in ('pending', 'verified', 'approved', 'rejected', 'cancelled')),
  new_status text not null check (new_status in ('pending', 'verified', 'approved', 'rejected', 'cancelled')),
  reason text not null,
  created_at timestamptz not null default now()
);

create index if not exists luar_referral_audit_referral_idx
  on public.luar_referral_audit(referral_id, created_at desc);

create table if not exists public.luar_referral_clicks (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique,
  referrer_user_id uuid not null references auth.users(id) on delete cascade,
  source text not null default 'link',
  created_at timestamptz not null default now()
);

create index if not exists luar_referral_clicks_referrer_idx
  on public.luar_referral_clicks(referrer_user_id, created_at desc);

-- Existing registrations stay verified. Only referrals with an already
-- confirmed LUAR lifetime payment become approved during the migration.
with purchased as (
  select distinct r.id
  from public.luar_referrals r
  join public.luar_payments p on p.user_id = r.referred_user_id
  where r.status = 'verified' and p.status = 'paid'
), promoted as (
  update public.luar_referrals r
  set status = 'approved',
      approved_at = coalesce(r.approved_at, now()),
      updated_at = now(),
      status_reason = 'existing_confirmed_purchase'
  from purchased p
  where r.id = p.id
  returning r.id
)
insert into public.luar_referral_audit
  (referral_id, actor_type, previous_status, new_status, reason)
select id, 'system', 'verified', 'approved', 'existing_confirmed_purchase'
from promoted;

alter table public.luar_referral_audit enable row level security;
alter table public.luar_referral_audit force row level security;
revoke all on public.luar_referral_audit from anon, authenticated;
revoke all on sequence public.luar_referral_audit_id_seq from anon, authenticated;
alter table public.luar_referral_clicks enable row level security;
alter table public.luar_referral_clicks force row level security;
revoke all on public.luar_referral_clicks from anon, authenticated;
revoke all on sequence public.luar_referral_clicks_id_seq from anon, authenticated;

comment on column public.luar_referrals.status is
  'pending=atribuida; verified=cadastro confirmado; approved=compra elegivel confirmada; rejected/cancelled=invalidada.';

comment on table public.luar_referral_audit is
  'Historico append-only de transicoes do programa de indicacoes, acessado somente pelo backend privilegiado.';

comment on table public.luar_referral_clicks is
  'Contagem idempotente de acessos a convites, sem IP, fingerprint ou recompensa por clique.';
