create table if not exists public.luar_referral_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  code text not null unique check (code ~ '^[A-Z0-9]{8,16}$'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.luar_referrals (
  id bigint generated by default as identity primary key,
  referrer_user_id uuid not null references auth.users(id) on delete cascade,
  referred_user_id uuid not null unique references auth.users(id) on delete cascade,
  referred_email text not null,
  source text not null default 'link',
  status text not null default 'verified' check (status in ('verified', 'cancelled')),
  verified_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  check (referrer_user_id <> referred_user_id)
);

create index if not exists luar_referrals_referrer_idx on public.luar_referrals(referrer_user_id, created_at desc);
alter table public.luar_referral_profiles enable row level security;
alter table public.luar_referrals enable row level security;
revoke all on public.luar_referral_profiles from anon, authenticated;
revoke all on public.luar_referrals from anon, authenticated;
revoke all on sequence public.luar_referrals_id_seq from anon, authenticated;
