const { articles, published, author } = require('./blog-data');
const esc = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const formatDate = value => new Intl.DateTimeFormat('pt-BR', { dateStyle: 'long', timeZone: 'America/Sao_Paulo' }).format(new Date(`${value}T12:00:00-03:00`));
const head = ({ title, description, canonical, type = 'website', schema }) => `<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0b0f0c"><title>${esc(title)} | LUAR</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1"><link rel="canonical" href="${canonical}"><meta property="og:locale" content="pt_BR"><meta property="og:type" content="${type}"><meta property="og:site_name" content="LUAR"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="https://luarhub.site/preview.png"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="https://luarhub.site/preview.png"><link rel="icon" href="/luarlogo.png?v=2"><link rel="manifest" href="/manifest.webmanifest"><link rel="stylesheet" href="/seo-pages.css"><link rel="stylesheet" href="/blog.css"><link rel="stylesheet" href="/public-share.css"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g, '\\u003c')}</script><script src="/tracking-config.js"></script><script src="/growth-tracking.js" defer></script><script src="/pwa-install.js" defer></script><script src="/public-share.js" defer></script></head>`;
const nav = `<header class="seo-nav"><a href="/"><img src="/luarlogo.png?v=2" alt="Logo oficial do LUAR" width="42" height="42"><b>LUAR</b></a><nav><a href="/recursos">Recursos</a><a href="/blog">Blog</a><a class="nav-cta" href="/#signup">Começar grátis</a></nav></header>`;
const footer = `<footer><a href="/">LUAR</a><p>Organização pessoal, produtividade e finanças em um só lugar.</p><nav><a href="/sobre">Sobre</a><a href="/contato">Contato</a><a href="/privacidade.html">Privacidade</a></nav></footer>`;
function renderIndex() {
  const canonical = 'https://luarhub.site/blog';
  const schema = [{ '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Início', item: 'https://luarhub.site/' }, { '@type': 'ListItem', position: 2, name: 'Blog', item: canonical }] }, { '@context': 'https://schema.org', '@type': 'CollectionPage', name: 'Blog do LUAR', description: 'Guias práticos sobre hábitos, produtividade, rotina, foco e finanças pessoais.', url: canonical, inLanguage: 'pt-BR' }];
  const cards = Object.entries(articles).map(([slug, a]) => `<article class="blog-card"><span>${a.readTime} min de leitura</span><h2><a href="/blog/${slug}">${esc(a.title)}</a></h2><p>${esc(a.description)}</p><a class="text-link" href="/blog/${slug}">Ler guia completo →</a></article>`).join('');
  return `<!doctype html><html lang="pt-BR">${head({ title: 'Blog sobre hábitos, produtividade e organização', description: 'Guias práticos e aprofundados para criar hábitos, organizar a rotina, controlar gastos, estudar e manter o foco.', canonical, schema })}<body>${nav}<main><section class="seo-hero blog-hero"><div><span>GUIAS PRÁTICOS DO LUAR</span><h1>Organização explicada para a vida real.</h1><p>Conteúdo original sobre hábitos, produtividade, estudos, foco, metas e finanças. Respostas diretas primeiro; contexto e exemplos depois.</p></div><aside><img src="/luarlogo.png?v=2" alt="Blog oficial do LUAR" width="160" height="160"><strong>Atualizado em ${formatDate(published)}</strong><small>Conteúdo assinado e revisado.</small></aside></section><section class="blog-grid" aria-label="Artigos do blog">${cards}</section><section class="seo-final"><h2>Coloque o que aprendeu em movimento.</h2><p>Experimente hábitos, tarefas, metas, foco e finanças no mesmo lugar.</p><a href="/#signup">Criar minha conta gratuita</a></section></main>${footer}</body></html>`;
}
function renderArticle(slug, a) {
  const canonical = `https://luarhub.site/blog/${slug}`;
  const schema = [{ '@context': 'https://schema.org', '@type': 'Article', headline: a.title, description: a.description, image: 'https://luarhub.site/preview.png', datePublished: published, dateModified: published, inLanguage: 'pt-BR', mainEntityOfPage: canonical, author: { '@type': 'Person', name: author }, publisher: { '@type': 'Organization', name: 'LUAR', url: 'https://luarhub.site', logo: { '@type': 'ImageObject', url: 'https://luarhub.site/luarlogo.png?v=2' } } }, { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Início', item: 'https://luarhub.site/' }, { '@type': 'ListItem', position: 2, name: 'Blog', item: 'https://luarhub.site/blog' }, { '@type': 'ListItem', position: 3, name: a.title, item: canonical }] }, { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: a.faq.map(([q, answer]) => ({ '@type': 'Question', name: q, acceptedAnswer: { '@type': 'Answer', text: answer } })) }];
  const sections = a.sections.map(([title, text], i) => `<section id="secao-${i + 1}" class="article-section"><h2>${esc(title)}</h2><p>${esc(text)}</p></section>`).join('');
  const faq = a.faq.map(([q, answer]) => `<details><summary>${esc(q)}</summary><p>${esc(answer)}</p></details>`).join('');
  const related = a.related.map(key => articles[key] ? `<a href="/blog/${key}">${esc(articles[key].title)} <b>→</b></a>` : '').join('');
  return `<!doctype html><html lang="pt-BR">${head({ title: a.title, description: a.description, canonical, type: 'article', schema })}<body>${nav}<main class="article-main"><article><header class="article-header"><nav class="breadcrumbs" aria-label="Navegação estrutural"><a href="/">Início</a><span>/</span><a href="/blog">Blog</a></nav><span>GUIA DO LUAR</span><h1>${esc(a.title)}</h1><p>${esc(a.description)}</p><div class="article-meta"><span>Por ${author}</span><time datetime="${published}">Publicado e atualizado em ${formatDate(published)}</time><span>${a.readTime} min de leitura</span></div></header><aside class="direct-answer"><strong>Resposta direta</strong><p>${esc(a.answer)}</p></aside><nav class="article-toc" aria-label="Sumário"><strong>Neste guia</strong><ol>${a.sections.map(([title], i) => `<li><a href="#secao-${i + 1}">${esc(title)}</a></li>`).join('')}<li><a href="#perguntas">Perguntas frequentes</a></li></ol></nav>${sections}<section id="perguntas" class="seo-faq article-faq"><header><span>PERGUNTAS FREQUENTES</span><h2>Respostas para continuar.</h2></header><div>${faq}</div></section><section class="article-cta"><span>TRANSFORME LEITURA EM AÇÃO</span><h2>Experimente o LUAR gratuitamente.</h2><p>Registre sua rotina, acompanhe o progresso e mantenha os dados conectados.</p><a href="/#signup">Começar agora</a></section><section class="seo-related"><span>CONTINUE APRENDENDO</span><h2>Guias relacionados.</h2><nav>${related}</nav></section></article></main>${footer}</body></html>`;
}
module.exports = async function handler(req, res) { const slug = String(Array.isArray(req.query.slug) ? req.query.slug[0] : req.query.slug || '').toLowerCase(); const html = slug ? (articles[slug] ? renderArticle(slug, articles[slug]) : null) : renderIndex(); if (!html) return res.status(404).send('Artigo não encontrado'); res.setHeader('Content-Type', 'text/html; charset=utf-8'); res.setHeader('Cache-Control', 'public, max-age=0, s-maxage=86400, stale-while-revalidate=604800'); return res.status(200).send(html); };
module.exports.articles = articles;
